### ISSUE TITLE
Create a sketch/framework/draft of a journey map

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#10]
As researcher, I want to sketch what I know right now about Ops to confirm what I know, fill in the gaps, give M&T something to react to, so that we can start thinking about features, what we know/don't know, and flesh out more detail for prototyping.

(In the future we will potentially break out sub-journeys for The Watch, Task forces, CMS, etc. This can also inform where things can be flattened, optimized, or equalized.)

AC: 
- [ ] Sketch initial journey map based on what we know and don't know (like the Zelda fog) we'll continue to add to it and flesh it out, break out sub-journeys

**Comment by karareinsel** [comment]
@matt-dobson has bandwidth and the sprint can accommodate the work so we're pulling this issue into sprint Ghana.

**Comment by beebouttw** [comment]
Alright!  Callback all the way to sprint Azerbaijan!

**Comment by karareinsel** [comment]
Closing out this issue because it has been replaced by #124 and #126.
