### ISSUE TITLE
Complete the interview with Joe Wicentowski

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#101]
AC

- [ ] Complete the interview with Joe Wicentowski

**Comment by beebouttw** [comment]
I reached out to Joe separately to pose the question of a "followup" interview in the hopes of getting a response from him.  Currently awaiting, possibly blocked.

**Comment by karareinsel** [comment]
Closing this out since we've made multiple attempts to schedule an interview but have not had success.
