### ISSUE TITLE
Onboard new 18F designers

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#103]
AC

- [x] Add new team members to stand-up's, retros, demos, backlog grooming and sprint planning
- [x] Existing designers and new designers set up dedicated time to go over work done to date and upcoming work
- [x] New designers and PMs set up dedicated time to go over work done to date and upcoming work
- [x] Add to the repos, docs, team calendar, and slack

**Comment by yowill** [comment]
Docs shared widely, added to calendars, slack, schedules, meetings booked. Fin.
