### ISSUE TITLE
Prepare for meeting with DOS on 2/7 - feedback recommendations and draft personas

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#104]
AC

- [x] Prepare any supporting materials and/or talking points for the meeting on 2/7

**Comment by brandocalrissian** [comment]
Prepare background on context for why we created draft personas and feedback recommendations

**Comment by yowill** [comment]
Comparisons to other orgs would be helpful

**Comment by yowill** [comment]
Timeline of project and how this fits in too

**Comment by yowill** [comment]
Describe what role the new designers will play

**Comment by yowill** [comment]
We are prepped! Closing this task.
