### ISSUE TITLE
Prepare for sprint ceremonies training

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#105]
AC:
- [x] Schedule sprint ceremonies training
- [ ] Prepare training materials

**Comment by yowill** [comment]
Along with M&T, Holly and Theresa Dixon (Tyler replacement) are super important to be in this.

**Comment by yowill** [comment]
12th or 13th works for Theresa (Holly is out all next week)

**Comment by karareinsel** [comment]
Slides from the training https://docs.google.com/presentation/d/1kmcG2mkT-Lh5Rhv3sgmYaAXpmI0bECqbl_DLQ7LraFk/edit
