### ISSUE TITLE
Refine/iterate the Chris the CMS officer proto-personas

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#108]
Based on the feedback received during the 2/7 session, refine and iterate on the proto-personas.

AC:
- [ ] Update Chris the CMS officer, answering their emotions during the journey mapping

**Comment by MeghanLuecke** [comment]
I added some edits to the Draft Persona Sketching shared doc based on our group meeting last week!

**Comment by yowill** [comment]
From journey mapping exercise, the process is more complicated than a single persona.
