### ISSUE TITLE
Schedule syncs with Ops Center PMs in training

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#109]
In order to teach the Ops Center PMs in training, we will have regular syncs to go over new concepts they are learning and practicing.

- [x] Determine the frequency of the syncs
- [x] Schedule the syncs

Support:
@MeghanLuecke 
@beebouttw 
@AshleyMS86

**Comment by MeghanLuecke** [comment]
Please schedule for AFTER Feb 25 to Ops absences. Thanks!

**Comment by karareinsel** [comment]
Schedule PM working session (15 - 30 minutes max) on stand-up's (review best practices, maybe do a stand-up simulation to practice) on 2/26 or 2/27 with the goal that the PM's in training (PMIT) will start leading stand-up on 2/28 or 3/1. We'll schedule a debrief for after the PMIT's have led a few stand-up's to offer feedback and refine.

**Comment by karareinsel** [comment]
The PM's in training are Tyler and Theresa for the Watch and Meghan for CMS.

The content managers in training are Ryan Voigtlaender for the Watch and Katherine for CMS.

**Comment by karareinsel** [comment]
The 18F PMs and Ops PMs have daily sync's starting on 2/25.
