### ISSUE TITLE
Create a base journey map

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#11]
As a researcher, I want to understand all the processes and workflows, emotions, pain points, and how they are gathering and disseminating information, so that the 18F team can identify processes that need to be formalized or documented, identify areas for change, and features needed.

Reference material:
Previous journey map drafting https://github.com/18F/dos-ops-center/issues/10

AC:

**Comment by yowill** [comment]
Breaking the start of this work out into #124, #125,  #126

**Comment by karareinsel** [comment]
Closing this out because it has been replaced by #124 .
