### ISSUE TITLE
Begin investigating possible KMS platforms

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#112]
As an 18F researcher, I want to create a working list of possible KMS platforms that could be appropriate for the Ops Center so that I can begin to evaluate their features and functionality agains Ops Center needs.

AC:
- [x] Build a list of viable KMS products, avoiding products that do not have enough market traction/momentum for a group to depend on in production (no DeLoreans) 
- [x] Explicitly list the conditions we're saying must be met (for sustainability) to be on this list

Support
@matt-dobson 
@brandocalrissian

**Comment by brandocalrissian** [comment]
We're going to create more swimlanes on the [KMS board](https://github.com/18F/dos-ops-center-kms/issues/24#workspaces/dos-ops-center-kms-5c264892f9cceb5e65c195ee/boards) to provide visibility as we evaluate and narrow down KMSs. Anyone on the team can comment on the tickets and see what platforms are still in contention in real-time.

**Comment by brandocalrissian** [comment]
eval criteria for first round
Basic viability
- [ ] is cloud-ready
- [ ] is FEDRAMPed
- [ ] is actively supported (with a release in the past year)
- [ ] has active developer community
- [ ] has customer support

**Comment by brandocalrissian** [comment]
We created three swimlanes on the [KMS board](https://github.com/18F/dos-ops-center-kms/issues/24#workspaces/dos-ops-center-kms-5c264892f9cceb5e65c195ee/boards): _KMS to evaluate_ (KMSs that need an evaluation pass), _KMS under consideration_ (KMSs that have passed evaluations thus far), _Rejected KMS_ (KMSs that have failed an evaluation). Added the _Basic viability_ checklist from above for the first round of evals and added a couple of example KMS entries to the swimlane.

**Comment by brandocalrissian** [comment]
In an evaluation pass, we'll move each KMS from the "to evaluate" to the "under consideration" or "rejected" lanes depending on how the evaluation goes.

**Comment by karareinsel** [comment]
Added @matt-dobson to this since he was already doing parallel work so and has started to add KMS to evaluate to the board.

**Comment by brandocalrissian** [comment]
Are we waiting on the evaluation for the products we have listed for basic viability until [this ticket](https://github.com/18F/dos-ops-center/issues/140)?

**Comment by brandocalrissian** [comment]
^^^ will do eval in #140. We can close this list once everyone on the team says the time is long enough.

**Comment by brandocalrissian** [comment]
Populating this list of products with an eye for Content Management Systems instead of Digital Asset Managers (DAMs) — DAMs have different strengths/priorities/focuses. We still have an open question if a DAM would be a good fit for Ops. Plan to add them to this list if we decide that's a path we should investigate further.

**Comment by brandocalrissian** [comment]
In open comment time for this ticket. Will close when everyone has had an opportunity to add any reasonable missed product.

**Comment by brandocalrissian** [comment]
Decided against adding flat file CMSs to the list because they feel like their target is web sites who don't need the "power" of WordPress.

**Comment by matt-dobson** [comment]
Does the "* is FEDRAMPed" checkbox make this a relatively small list?

I've looked at the FedRAMP marketplace, but I'm not sure which if any of the approved products are relevant. Is there another place to find out products that will meet that criteria?

How can we best contribute to this list of possible KMS solutions considering the FedRamp requirement? If the FedRamp approved options are inadequate how do we identify other possibilities?

**Comment by matt-dobson** [comment]
> Digital Asset Managers (DAMs) — DAMs have different strengths/priorities/focuses. We still have an open question if a DAM would be a good fit for Ops.

@brandocalrissian do you have examples of how you think a DAM might be used? And what assets would be managed? If it is relevant to the SOS or other products we are mapping we can make sure we capture how assets (images? other media?) are handled currently.

**Comment by karareinsel** [comment]
I added a few more CMS to consider.

**Comment by karareinsel** [comment]
@matt-dobson A DAM could be used potentially for storing more evergreen/canonical assets. They have a limited number of visual assets but they have a lot of assets that are evergreen and could be easily/well supported by a DAM. I used a DAM in the past to serve as a portal for brand and marketing materials - not unlike the guidance/reference assets that CMS produces. It's an idea to consider/food for thought at this point.

**Comment by brandocalrissian** [comment]
Closing this as we've had the call for additions out for a while.
