### ISSUE TITLE
Update readme & glossary on DOS Github

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#113]
As an 18F team members and someone in the public who wants to know about the project, I want to have up to date (as well as we know at the moment) information about the timelines and team members of the project in the readme on https://github.com/18F/dos-ops-center so that we have accurate information and expectations on the timeline (especially post-shutdown changes).

AC:
- [x] Update timelines / projected milestones
- [x] Update team members
- [x] Add and update Ops galaxy map (?) https://app.mural.co/t/gsa6/m/gsa6/1549638946944/31c5db76892da191d3928c91e98de2021a0ea310
- [x] Update glossary with more acronyms especially around positions
- [x]  Add some info linking the KMS repo in the readme

**Comment by MeghanLuecke** [comment]
Hey @yowill, updating projected timelines and estimated dates for key deliverables is a priority internal issue on my end as well, so would be glad to stay in touch on this!

**Comment by yowill** [comment]
Updated sprint ceremonies too
