### ISSUE TITLE
Testing and refining output from the 2/9 content modeling session

### ISSUE THREAD

**Issue by RyanSibley** [18F/dos-ops-center#114]
As a member of the operations center, I need to understand how to categorize the products we create in ways that make sense to audiences both internal to ops and external to ops. I also need to understand when and how (what the rules are) to categorize a product.

AC
- [x] * 18F and Ops teams work together to identify various categorization options based on input gathered from the content modeling sessions held during the last sprint (sprint France).
- [x] * 18F and Ops teams work together to brainstorm other ways to categorize  products outside of what was identified during the content modeling sessions.
- [x] * 18F and Ops teams work together to hash out ambiguities in language that could cause confusion when trying to structure a database.
- [x] * Create rules for placing a product in potential categories.

Background:
Using information generated during the 2/9/19 content modeling session, test ideas that could inform how and what to focus on for the content strategy and knowledge management system. 

Mural from modeling session here: https://app.mural.co/t/gsa6/m/gsa6/1549648808314/19b165c40aea30371d8451cb8263310c107be8d5

Previous issue here: https://github.com/18F/dos-ops-center/issues/72

related materials: https://docs.google.com/document/d/1ntN5p0fLsHNXRPToTs0QtBs4UBKRt3snXWHLFkaagGs/edit#

Support:
@durland18F

**Comment by MeghanLuecke** [comment]
I've added more products and made a few adjustments based on subsequent "speed" content modeling sessions.

**Comment by RyanSibley** [comment]
Updating to highlight that this work should also involve the data gathered by Meghan and Tyler during the "speed sorting" sessions.

**Comment by RyanSibley** [comment]
As a member of the operations center, I need to understand how to categorize the products we create in ways that make sense to audiences both internal to ops and external to ops. I also need to understand when and how (what the rules are) to categorize a product. 

AC

- 18F and Ops teams work together to identify various categorization options based on input gathered from the content modeling sessions held during the last sprint (sprint France).  

-  18F and Ops teams work together to brainstorm other ways to categorize  products outside of what was identified during the content modeling sessions. 

-  18F and Ops teams work together to hash out ambiguities in language that could cause confusion when trying to structure a database. 

-  Create rules for placing a product in potential categories.

**Comment by RyanSibley** [comment]
Update: Further testing will likely occur after we do the journey mapping exercise. To continue to add to the knowledge we gained during the content modeling exercises we'd like to start to identify and collect the elements of metadata for each product. 
For instance: 
What is the final intended audience for this product?
Name [Safety Overseas Summary]
Title [Safety Overseas Summary February 24, 2019] 
Regional categorizations
Into what system does this product go? [The Line, email distribution]
To whom does the product go? [To clarify: it might be for the secretary, but it’s going to the Line. We want to know the latter for routing purposes.]

**Comment by RyanSibley** [comment]
I'm gathering potential metadata elements here: https://docs.google.com/spreadsheets/d/1mFvUdWxCzK_aMavUhJyEkjgMgIVcDFBXt0yuouOYa7Q/edit#gid=489212529

**Comment by MeghanLuecke** [comment]
I requested access to the metadata doc in Google.

**Comment by RyanSibley** [comment]
More notes here: https://docs.google.com/document/d/1mTQjOADqCYGocyhXcylpzVo2hDTeAQ_Q43u5md0EBdc/edit

**Comment by RyanSibley** [comment]
Notes:
Regarding hashing out language ambiguities:
- Say `content types` and not `products` as much as possible. 

- `Crisis` can potentially be defined and used a indicator regarding how to treat content types in a database

**Comment by RyanSibley** [comment]
Through working sessions intended to identify themes that surfaced in the content modeling sessions, and through much conversation, we've decided to use a set of categorizations that is rooted in sorting content-types by their intended purpose or function.  This will be the preliminary set, and will almost certainly change after more research and testing. Regardless of any changes, we hope that this model will get us the path to identifying a model that allows people to discover information that they might otherwise miss, promote curiosity and  enable people to learn about other work happening. 

The preliminary set of categories is: 

<img width="178" alt="screen shot 2019-02-27 at 2 19 33 pm" src="https://user-images.githubusercontent.com/1151139/53516645-c53d1500-3a9a-11e9-9b64-d9c766cd3dda.png">

**Comment by MeghanLuecke** [comment]
Here are updated product/content material TYPES for use in testing - some of these are unchanged, but some needed to be more specific for use in testing (i.e. the term "Action Memo" on its own is too broad for a tester to categorize without context). Then, further down, are a list of actual examples we could also consider for use in testing. 

CONTENT MATERIAL/"PRODUCT" TYPES
SOS
Weekend Watching
Watch Log
TF Log
Briefs
Alters
Memcon
Transcript
EXDIS
NODIS 
Incidents and Threats
S/P/D Call updates
Phone directory
Triple dots
Task Force Talking Points
Task Force Call Notes
Lessons Learned
Summary of Conclusions "SOC" (SCORE)
SOC (for Watch processing)
Briefing Checklist for Ops FO
Action/Decision/Info Memo (SCORE)
Action/Decision/Info Memo (FO/Management issues)
Action/Decision/Info Memo (CMS regional issues)
Action/Decision/Info Memo (from another office, for Ops clearance)
Task Force ALDACs
Non-TF CMS ALDACs
ALDACs for Watch processing
Annotated Agenda (SCORE)
Issue Papers (SCORE)
SitRep (Task Force)
Department Notice (Task Force)
ExecSec Brief
Shift-to-shift notes (Watch)
Shift-to-shift notes (CMS TF)
IA Paper for Watch Processing
IA Paper for CMS Reference
Guidance (Watch)
Guidance (CMS Internal)
Guidance (CMS Outward-facing)

Specific Example Options (NOT comprehensive - not every content item above is included in examples below, and we have multiple examples for certain content items): 
SCORE SOC on Nairobi
Annotated Agenda for December 3 SCORE Meeting
Hurricane Task Force Sit Rep No. 3
SOS January 15, 2019
TF Call Notes from 1100 DoD Call
Ebola Lessons Learned
Management-Related Action Memo for the Exec Sec
BCL for Bob on an Interagency Coordination Meeting on Venezuela
BCL for Bob on an Interagency Coordination Meeting on Haiti
Brief on Clashes between India and Pakistan
Targeted Alert on Guaido Announcement
Guidance on Drafting Task Force SitReps
Guidance on Handling CRITICS
Guidance on Patching Secure to WHSR
Guidance on Managing TF Volunteers
Guidance on Clearing Weekend Watching
Guidance on Editor Chair
