### ISSUE TITLE
Speed testing with Belinda

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#115]
As an 18F researcher, I want to expose Belinda to the content modeling session to get her raw outputs so that we can better understand The Watch perspective

AC:
Prepare the resources for the session (cards and materials)
Schedule a 15 minute session with Belinda in person

**Comment by MeghanLuecke** [comment]
Ready to schedule this whenever the team is!

**Comment by MeghanLuecke** [comment]
Schedule for Belinda speed content session:

Friday 2/15 930 am

**Comment by karareinsel** [comment]
Done!

**Comment by beebouttw** [comment]
Interview conducted, new issue for recording findings and synthesizing.
