### ISSUE TITLE
Confirm details for setting up AWS account through the Cloud PMO 

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#116]
As an 18F researchers, I want to get all the details about how AWS accounts are created by the Cloud PMO within State Department so Ops can make an informed decision to go with it or to go with Cloud.gov (and how to get the $ obligated to Cloud.gov currently in the contract to move it over). 

AC:
- [ ] How much does it cost?
- [ ] Finalize the setup process
- [ ] How is money transferred inside the agency? 
- [ ] Is it sandbox vs production ready?  

Support:
@karareinsel 
@beebouttw

**Comment by MeghanLuecke** [comment]
Money would be transferred to 18F per existing contract, then from 18F to IRM (through a somewhat convoluted mechanism). We can provide further details once we get closer to a decision, and will need to connect Ops and EX directly with the Cloud PMO team to discuss if we end up going this route. It will depend somewhat on the pricing information and other AC for this issue.

**Comment by karareinsel** [comment]
Have we had any success getting answers to these questions?
- [ ] How much does it cost?
- [ ] Finalize the setup process
- [ ] Is it sandbox vs production ready?

**Comment by karareinsel** [comment]
@tadhg-ohiggins quickly checking in - were you able to email Kenny with your questions? If so, did he respond?

**Comment by MeghanLuecke** [comment]
Also @tadhg-ohiggins - we are planning to set up a quick call with Alen to double-track the same questions you had planned to send to Kenny. @beebouttw is setting up

**Comment by MeghanLuecke** [comment]
@karareinsel @tadhg-ohiggins @beebouttw Meghan will set up a follow-up call to confirm estimated cloud-related pricing. Kara will find a time for us to speak as a group (hopefully late Monday) to compare notes, review the criteria for choosing which cloud service to use, and make a decision.

**Comment by yowill** [comment]
These answers have not been clear, they're still building out the system and costs aren't clear yet (they will just pass on the costs), so it's a little early for that solution. We've made the recommendation, opening a cloud.gov sandbox! 

There will be future follow up for Ops to investigate some of these money/infrastructure issues.

**Comment by karareinsel** [comment]
- [ ] How much does it cost? Exact costs are TBD but we understand the cost for a test DOS cloud account are nominal. Costs for a product DOS cloud account are very much uncertain. Michelle Sparrow-Walker confirmed they would be charged for utilization and consumption in the near-term.
- [ ] Finalize the setup process N/A Using cloud.gov for the test environment. Path to setting up a production cloud at DOS is still uncertain and will be pursued in a parallel path by Ops.
- [ ] How is money transferred inside the agency? @MeghanLuecke 
- [ ] Is it sandbox vs production ready? DOS cloud is kind of sandbox ready but not production ready.
