### ISSUE TITLE
Speed content testing with Will C, Brian H, Nakeya B, and David G

### ISSUE THREAD

**Issue by MeghanLuecke** [18F/dos-ops-center#117]
As an Ops researcher, I want to expose additional stakeholders to content modeling to get their raw outputs and also test existing drafts so that we can better understand the Leadership (Will and Brian) and Administrative (Nakeya and David) perspectives. 

AC:

- [x] Prepare the resources for the session (cards and materials)
- [x] Schedule a 30 minute session in person or over the phone (this could be as a whole group or in two groups)

**Comment by karareinsel** [comment]
@MeghanLuecke can you add the updated schedule to this issue?

**Comment by MeghanLuecke** [comment]
Yep, thanks Kara! Here's the schedule: 

1pm 2/13: David and Nakeya (Admin Team)
2pm 2/13: Will and Cobb (Management - this group doesn't include Ashley since she already participated once)

Please note the Belinda speed content session is a separate issue and scheduled for Friday 2/15 at 930am ET.
