### ISSUE TITLE
Establish interview days and times for Meghan and Tyler to book

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#12]
As an 18F researcher, I want to get the interviews days and times set up so that we can plan our travel, interview sessions, get the right subjects in the room for interviews, so that we can have a super-effective interview session the week of Nov. 5.  

AC: 
- [x] Send M&T our windows of time available (times and days) 
- [ ] Confirm that everything is good to book and go!
- [ ] Conference room booking through M&T

**Comment by hannahkane** [comment]
Here's our preferred schedule for next week's interviews.
9:30 - 10:30
11:00 - 12:00
1:00 - 2:00
2:30 - 3:30
4:00 - 5:00
