### ISSUE TITLE
Identify Watch products that will be produced through InfoViewer

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#121]
As an 18F researcher, I would like to know which Watch products will be produced through InfoViewer so that I can understand if/how they will interact with the KMS and possible user testing needs.

AC

- [x] Ops team to provide a list of products that will be produced through InfoViewer

**Comment by beebouttw** [comment]
InfoViewer operates on the wider internet, rather than OpenNet, so classification is limited to Unclassified only.  For that reason, the only product the Watch can publish through InfoViewer is News Tickers.

**Comment by karareinsel** [comment]
Beyond using InfoViewer to produce the news tickers, will Ops customers be encouraged to use or directed to use InfoViewer for other types of information?

**Comment by beebouttw** [comment]
Ops customers will be able to use InfoViewer's distribution service to receive news tickers in their email inbox, either individually or in digest form.  The content and delivery frequency of those tickers will be determined by the customer's preference.

Furthermore, Ops customers can visit the main page at state.infodesk.com to browse news being updated in real time and search news for their selected topics.
