### ISSUE TITLE
Obtain samples of all the products that were documented in the content bucketing sessions

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#122]
As an 18F researcher, I would like to see samples of all of the products that were documented in the content bucketing session so that I can understand the full scope of products that are produced by the Ops Center and identify user needs and potential testing opportunities.

AC
- [x] Send over Ashley's github username so we can assign this to her
- [x] Ops provides samples of all of the products listed in the mural board under the "raw list of products" cards https://app.mural.co/t/gsa6/m/gsa6/1550088919683/5c0ae43646fd6adf6322744b8578465b8174ed18

Support
@AshleyMS86

**Comment by MeghanLuecke** [comment]
We have blockers for some items due to classification but can provide scrubbed templates or mock-data samples. We should discuss the intended scope in order to define the point estimate, but this is a time-consuming (though not actually difficult) task on the CMS side. I am looking at getting some additional help on the CMS side for this!

**Comment by brandocalrissian** [comment]
We have copies of some content products since the PA. Perhaps we should add a list of what we have already to this ticket?

**Comment by MeghanLuecke** [comment]
Brandon I was just looking for those - it would be great if you guys could confirm which samples 18F already has!

**Comment by karareinsel** [comment]
We have samples of the following:

- Ops Digest
- General Alerts
- Safety Overseas (SOS)
- Situation Report from a hurricane task force
- News tickers

**Comment by beebouttw** [comment]
Full List of Still-Needed Products.

The Watch:
- [ ] Watch Log
- [ ] Brief
- [ ] Guidance
- [ ] General Alert
- [ ] Targeted Alert
- [ ] Memcon
- [ ] Transcript
- [ ] EXDIS
- [ ] NODIS
- [ ] InterAgency Paper
- [ ] Incidents and Threats
- [ ] S/P/D Call Updates
- [ ] ExecSec Written Brief
- [ ] Shift-to-Shift Notes
- [ ] Phone Directory
- [ ] Triple Dots
- [ ] SitRep/SpotRep
- [ ] ALDAC
- [ ] InterAgency SOC (From PC/DC Meetings)
- [ ] Travel Records
- [ ] MOTR
- [ ] CRITIC
- [ ] Administrative Record
- [ ] Payroll Record
- [ ] Personnel Schedule

CMS:
- [ ] Annotated Agenda
- [ ] SOC (SCORE)
- [ ] Issue Paper
- [ ] Decision Memo
- [ ] Taskforce Press Guidance
- [ ] Briefing Checklist
- [ ] Taskforce Call Notes
- [ ] Lessons Learned
- [ ] Weekend Watching
- [ ] SitRep
- [ ] ALDAC
- [ ] Guidance
- [ ] Department Notice
- [ ] Action Memo
- [ ] Taskforce Log
- [ ] Info Memo
- [ ] Administrative Record
- [ ] Template
- [ ] Travel Record
- [ ] Payroll Record
- [ ] Personnel Schedule

**Comment by beebouttw** [comment]
[2009 Declassified NODIS Cable.pdf](https://github.com/18F/dos-ops-center/files/2885835/2009.Declassified.NODIS.Cable.pdf)
