### ISSUE TITLE
Prioritize Ops Center content products

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#123]
As an 18F researcher, I would like to understand the priority of all of the content products Ops produces and/or is responsible for so that we can align the level of effort (LOE) to produce with the level of impact (LOI)of the product. The outcomes will be used to prioritize user testing and user needs for both the content strategy and the KMS functionality. 

AC
- [x] Schedule working session with the Ops team
- [x] Ops and 18F teams evaluate each product in terms of LOE and LOI to assess prioritization

Support
@brandocalrissian 
@matt-dobson 
@vishaliyer-18f

**Comment by yowill** [comment]
Try to schedule this for next week in DC

**Comment by karareinsel** [comment]
The Watch LOE working session is 2/22, 2:30 - 3:30 ET.

**Comment by karareinsel** [comment]
The Watch LOI working session is 2/27, 2:00 - 3:00 ET.

**Comment by karareinsel** [comment]
Document that will be used during the working sessions - https://docs.google.com/document/d/1vcBtw4a8zUzV8XgjrHNPJPD9JCofwTVyrNE2a6kAhqQ/edit#heading=h.nctfd7a8mm80

**Comment by karareinsel** [comment]
The CMS working sessions are - 

- Tuesday, 2/26, 1:00 - 2:00 (LOE)
- Wednesday, 2/27, 2:00 - 3:00 (LOI)

**Comment by brandocalrissian** [comment]
Watch LOE working session completed.

**Comment by brandocalrissian** [comment]
Document for the CMS working sessions: https://docs.google.com/document/d/1efCAYt16FJkpPjqia5r1tUcd-G3Qyx4DBfOU1dI2ejo/edit

**Comment by brandocalrissian** [comment]
Watch LOE session results turned into a scoring spreadsheet (will share after the CMS session to prevent "spoilers")

**Comment by brandocalrissian** [comment]
CMS LOE session completed this afternoon (EDT).

Put the initial synthesis pass for both LOE sessions into [a scoring spreadsheet](https://docs.google.com/spreadsheets/d/1VMpcleX_MjT7gz0uHACAkTpxUQ5jqmeqTjZrKuOPDI0/edit) that has not been reviewed/vetted fully by anyone else (so it may change some).

**Comment by brandocalrissian** [comment]
Added the LOI session data to the scoring spreadsheet. Did initial rough scatter plots for both sets of products.

**Comment by beebouttw** [comment]
Just checked out the spreadsheet -- very cool stuff so far.  Thanks for making this available to us!
