### ISSUE TITLE
Start fleshing out the SOS journey map 

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#125]
As an 18F researcher, I want to detail the SOS production journey map so that I can understand one of the biggest and most used products, and create a model for future product journey maps to compare across the full content view of all the swim lanes.

Resources:
Early work-in-progress mural: https://app.mural.co/t/gsa6/m/gsa6/1549979944825/c01105ea9f3cc40f5135a3161d6dbdda0939a6e5

AC:
- [x] Post an example of the SOS product
- [x] Create it's steps across the journey map 
- [ ] Verify with DOS team that our assumptions and observations are correct via the working session

Support:
@durland18F 
@yowill 
@RyanSibley 
@jeanninehunter

**Comment by karareinsel** [comment]
A sample of the Safety Overseas Summary (SOS) is found on page 3. https://drive.google.com/drive/folders/1EGKHUH9d_VaJFh9kEEMewVz5vQRIT9P7

**Comment by MeghanLuecke** [comment]
We will be sure to get Holly's input as the primary drafter these days, plus Catherine when she's up on GitHub!
