### ISSUE TITLE
Prepare for SOS journey map working session

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#127]
As an 18F researcher, I need to prepare for the working session we will do with the Ops team to work through and complete the draft SOS journey map.

AC

- [x] Identify questions for the different steps of the journey map
- [x] Identify knowledge gaps that we want to fill through the journey map
- [x] Prepare a skeleton of the journey map which might include the axes, categories, users
- [x] Identify outstanding questions that still remain to be answered going forward
- [x] Collect supplies
- [x] Prepare logistical plan for the session
- [x] Identify goals and shared objectives

Support 
@ CMS folks (Catherine, @MeghanLuecke )
@yowill 
@RyanSibley 
@jeanninehunter 
@durland18F

**Comment by yowill** [comment]
Draft document preparing questions and needs here: https://docs.google.com/document/d/1LdCgw17VrW7h0rlFiBEDwSAUkfX0liidbiDI8xdyL38/edit

**Comment by matt-dobson** [comment]
Skeleton for SOS journey map is here:
[https://app.mural.co/t/gsa6/m/gsa6/1551186978836/d0cb8fa915f36199b8d0c7bcbccd49a74ec39e90](https://app.mural.co/t/gsa6/m/gsa6/1551186978836/d0cb8fa915f36199b8d0c7bcbccd49a74ec39e90
)
