### ISSUE TITLE
Synthesize Speed Bucketing Results

### ISSUE THREAD

**Issue by beebouttw** [18F/dos-ops-center#129]
As an Ops researcher, I want to compile, document, and synthesize inputs from Will, Brian, David, Nakeya, and Belinda's speed bucketing sessions to develop an initial draft of taxonomy for information management schema.

**Comment by yowill** [comment]
@beebouttw is this done with the work Meghan did for the Demo on Friday? Or is this a larger taxonomy project we need to prioritize?

**Comment by beebouttw** [comment]
@yowill Looking at the documents Meghan put together, I believe this is done.
