### ISSUE TITLE
Identify the final list of research subjects

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#13]
As an 18F researcher, I want to formalize the final list of research subjects and organizational divisions so that we are effective and broad in our information collection the week of Nov. 5 at State.

Reference material:
Current running list https://docs.google.com/document/d/1aKoj9LwzEW7N_7I6-PVeAEDe_ZrZabE0G6IdfrqEXDc/edit

AC:
- [x] Monday meeting check with M&T on the research subject list feedback
- [ ] Get M&T to start booking times

**Comment by yowill** [comment]
Updated list received, we'll send feedback soon!

**Comment by karareinsel** [comment]
Capturing our comments and feedback on the list- https://docs.google.com/document/d/1fVOU2fUqcX4FPH91wdbRBZTitAy0d_AWLb6AF6Bu_Hs/edit

**Comment by karareinsel** [comment]
Updated list from M&T with our notes - https://docs.google.com/document/d/10XrSLS6dLebdnSRE-S0FvbHJvTIwn5xRIa9uE-GdrrQ/edit
