### ISSUE TITLE
Explore using Airtable for content modeling and prototyping

### ISSUE THREAD

**Issue by durland18F** [18F/dos-ops-center#130]
As an 18F researcher, I would like to explore how to use Airtable as a tool for testing so that I can test different content models or a possible test database of products.

Scope box:

AC:
- [ ] Investigate Airtable's ability to do thing we need (TBD)

**Comment by durland18F** [comment]
Determine if Airtable is a viable tool to model the structure of the KMS, so that we can use it to understand better what a prototype might look like.

**Comment by yowill** [comment]
We should check in with others in 18F that are experimenting with this to learn from their experience and models they're testing to stand on the shoulders of their research and feedback. I know Product is experimenting with this as a knowledge base map tool. And I think I heard Design was kicking the tires in different ways too?

**Comment by yowill** [comment]
being used for meta data and search
