### ISSUE TITLE
Research how other government operations centers manage their content

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#132]
As an 18F researcher, I would like to understand how other government operations centers manage their content to potentially uncover innovative methods, tools, and processes that could be applicable to the Ops Center.

Time Boxed: 30 minutes
Scope Boxed: Focus on features (tagging, collaborative working spaces, etc.)

AC:
* [x]   Chat with Tyler about the landscape he's seen

**Comment by yowill** [comment]
Scheduled for Tuesday at 11:30 a.m. EST https://meet.google.com/hdb-dagz-szr?authuser=1&hs=122
