### ISSUE TITLE
Develop tests that are based on output from content modeling sessions

### ISSUE THREAD

**Issue by RyanSibley** [18F/dos-ops-center#133]
As an 18F researcher, I want to conduct further research from the content modeling sessions output so that I can find models to test with users

AC:
- [ ] Take output from #114 to create something to test

Support:
@durland18F 
@jeanninehunter

**Comment by karareinsel** [comment]
Quick question - is more research necessary to identify things to test from the content modeling? I feel like we're at a point where we have enough information to identify possible tests. It's also possible I could be misunderstanding how this issue was written, that we are saying that we're identifying the things to test rather than identifying more research to do in order to figure out what to test.

**Comment by RyanSibley** [comment]
Maybe we should talk about this during coworking to make sure we're on the same page. I can't think of more research, per se, but some testing ideas have been put off in favor of what we might learn through journey mapping. That aside, I'm currently working through the information we gathered from the content modeling sessions to create a way to validate it and improve upon it.

**Comment by RyanSibley** [comment]
Based on work captured in #114 we'd like to design a test surrounding this list of categories: 

<img width="178" alt="screen shot 2019-02-27 at 2 19 33 pm" src="https://user-images.githubusercontent.com/1151139/53517509-c8390500-3a9c-11e9-8b3e-c887eaaf27d1.png">

We're envisioning a simple test where we use real names of content types, such as `Exec Sec Briefing, Feb 27, 2019` and ask people:

"Would you select any of these categories in your search for [sample content type]?"

Mechanics:

- Assuming this test (research) will happen on paper, we'll give people a highlighter so they can highlight the categories that make sense to them as they pretend to begin a search for the sample product type. 

- We'll test with people individually.

- We'll test with as many people from inside of Ops as possible. The tests will be quick and will hopefully not require formal scheduling. 

Things to think about/decide:
- Do we have tech available to us as we put this together?
- Who will be present to conduct the tests?
- Can we build learnings from the journey mapping session into this?
- Can we validate or gather even more metadata elements during this research?
 
cc @durland18F @vishaliyer-18f @matt-dobson

**Comment by RyanSibley** [comment]
From @MeghanLuecke:

Here are updated product/content material TYPES for use in testing - some of these are unchanged, but some needed to be more specific for use in testing (i.e. the term "Action Memo" on its own is too broad for a tester to categorize without context). Then, further down, are a list of actual examples we could also consider for use in testing. 

CONTENT MATERIAL/"PRODUCT" TYPES
SOS
Weekend Watching
Watch Log
TF Log
Briefs
Alters
Memcon
Transcript
EXDIS
NODIS 
Incidents and Threats
S/P/D Call updates
Phone directory
Triple dots
Task Force Talking Points
Task Force Call Notes
Lessons Learned
Summary of Conclusions "SOC" (SCORE)
SOC (for Watch processing)
Briefing Checklist for Ops FO
Action/Decision/Info Memo (SCORE)
Action/Decision/Info Memo (FO/Management issues)
Action/Decision/Info Memo (CMS regional issues)
Action/Decision/Info Memo (from another office, for Ops clearance)
Task Force ALDACs
Non-TF CMS ALDACs
ALDACs for Watch processing
Annotated Agenda (SCORE)
Issue Papers (SCORE)
SitRep (Task Force)
Department Notice (Task Force)
ExecSec Brief
Shift-to-shift notes (Watch)
Shift-to-shift notes (CMS TF)
IA Paper for Watch Processing
IA Paper for CMS Reference
Guidance (Watch)
Guidance (CMS Internal)
Guidance (CMS Outward-facing)

Specific Example Options (NOT comprehensive - not every content item above is included in examples below, and we have multiple examples for certain content items): 
SCORE SOC on Nairobi
Annotated Agenda for December 3 SCORE Meeting
Hurricane Task Force Sit Rep No. 3
SOS January 15, 2019
TF Call Notes from 1100 DoD Call
Ebola Lessons Learned
Management-Related Action Memo for the Exec Sec
BCL for Bob on an Interagency Coordination Meeting on Venezuela
BCL for Bob on an Interagency Coordination Meeting on Haiti
Brief on Clashes between India and Pakistan
Targeted Alert on Guaido Announcement
Guidance on Drafting Task Force SitReps
Guidance on Handling CRITICS
Guidance on Patching Secure to WHSR
Guidance on Managing TF Volunteers
Guidance on Clearing Weekend Watching
Guidance on Editor Chair

**Comment by karareinsel** [comment]
@RyanSibley is the idea to use the products above and ask "Where would you look to find this product?" and reference the five categories that you have listed at the top? For consistency, we should align this list of product with the products that were prioritized as part of #123 so that we're using the same set of products and to focus on products that are highly prioritized.

**Comment by RyanSibley** [comment]
Thanks so much for the idea! I'll look closer at what Meghan shared to see if any of the real world examples already work to represent the prioritized list and go from there. 

Below is the idea for the test that I also put in the comments above:
Based on work captured in #114 we'd like to design a test surrounding this list of categories: 

<img width="178" alt="screen shot 2019-02-27 at 2 19 33 pm" src="https://user-images.githubusercontent.com/1151139/53517509-c8390500-3a9c-11e9-8b3e-c887eaaf27d1.png">

We're envisioning a simple test where we use real names of content types, such as `Exec Sec Briefing, Feb 27, 2019` and ask people:

"Would you select any of these categories in your search for [sample content type]?"

**Comment by karareinsel** [comment]
Is it ok with you if I update #136 with this information since this is the test to come out of the content modeling sessions?

**Comment by MeghanLuecke** [comment]
@RyanSibley @karareinsel Thanks for these updates! I'd recommend we pare down the name of the second bucket to just read "Published Ops Materials" for testing purposes (to avoid giving too much guidance on what belongs there). What do you think? I also would be curious to try testing the region-based model IF we find we get confusion or inconsistent results on the function-based model.

**Comment by durland18F** [comment]
Speaking for myself and Ryan, we think it would be fine to update #136 with that info and we think it is a great idea to use "Published Ops Material."

**Comment by karareinsel** [comment]
I'll update #136. And I agree with the suggestion to maybe test the region-based model if we find confusion with the function-based model.

**Comment by durland18F** [comment]
W/r/t "align this list of product with the products that were prioritized as part of #123"

I have made a document to start reconciliation: https://docs.google.com/spreadsheets/d/1ZcNMWX4hyHPMNC_R-7wjvfP9WuEFlexu9694SmtbI-w/edit#gid=0

**Comment by RyanSibley** [comment]
From a work session with Jeff, Matt and Ryan: 
![image from ios](https://user-images.githubusercontent.com/1151139/53591845-000a8000-3b63-11e9-88cb-27f7f1025d79.jpg)

With this photo and the discussion above, we're going to call this closed and move to #136
