### ISSUE TITLE
Parse Will's responsibilities for Meghan and Tyler while he's out

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#138]
As Will, I need to breakdown what makes sense for Meghan and Tyler to own while I'm out, so that they can learn more about PMing, but also have a managable workload. 

AC:
- Create a breakdown of how things will parse between M&T and Kara backfilling
- Talk to everyone and get them set up for success

Support:
@karareinsel 
@beebouttw 
@MeghanLuecke 
@SwansonCL

**Comment by catherine** [comment]
Catherine will just have to pick a different username since this one is taken 😉I get tagged in a lot of open source projects.

**Comment by MeghanLuecke** [comment]
Added SwansonCL

**Comment by yowill** [comment]
Notes from backlog grooming that might influence some of this work on Sprint Jordan (and potentially beyond):
- Content Strategy getting the team up to speed, identifying some opportunities 
- Engaging leadership for feedback on KMS / vendor potential options 
- Helping get a sandbox environment set up for KMS prototype testing
- KMS LOI efforts

**Comment by yowill** [comment]
Issues #175  and #174 created for consideration in Sprint Jordan based on comment above

**Comment by yowill** [comment]
After conversations earlier today and yesterday, State is reducing some of their time in ceremony meetings. They've been invited to everything and are welcome to keep their participation level at the current state; given the reduced visibility by reducing attendance, Kara will still keep the reigns on the major Sprint ceremonies such as backlog grooming and sprint planning, while of course welcoming State's participation in helping lead them when they are available. So I think this can be closed. 

Cc @MeghanLuecke @beebouttw
