### ISSUE TITLE
Prepare for design studio of journey map research

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#139]
AC:
- [ ] Prepare a paper design studio working session with Ops around discrete functions and needs surfaced from the journey map for SOS.

**Comment by brandocalrissian** [comment]
Who will participate in the design studio?

**Comment by matt-dobson** [comment]
@brandocalrissian I think this sort of exercise works well with 8-12 people who have a diverse set of perspectives and expertise. I think we'd want a mix of 18F and State partners.

Here is a method card if it is helpful: https://methods.18f.gov/discover/design-studio/

I'm imagining the in-person large group exercise would only be a couple of hours and that a much smaller subset of the team (maybe 2 people) would refine the sketches and start designing prototypes afterwards. 

Can we mark this issue as a placeholder for a prototyping conversation?

**Comment by karareinsel** [comment]
At the end of this sprint (Iran), I think we will have enough information to identify testing/prototyping opportunities at least for discrete functionality/features/questions, without the need to do a design studio. The design studio feels like an extra step/nice to have but not a must-have.
