### ISSUE TITLE
Take KMS under consideration list and evaluate viability

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#140]
AC:
- [ ] Take the KMS under consideration list (fedramp, other features, etc.) and start lining them up against critical needs and features coming out the journey mapping and product prioritization sessions

Support:
@tadhg-ohiggins 
@karareinsel 
@MeghanLuecke 
@beebouttw 
@matt-dobson

**Comment by MeghanLuecke** [comment]
@karareinsel - just wanted to clarify, is this issue going to ultimately produce the market research report? Or will that come later in the project?

**Comment by brandocalrissian** [comment]
First cut for all: find out which products are FedRAMPed. Ones that aren't can be thrown on the rejected list. Propose we edit the checklist to ~strike~ the qualification item to track which one was the decisive determinant.

**Comment by brandocalrissian** [comment]
@MeghanLuecke This effort is market/fit research and should be a source for the related report.

**Comment by karareinsel** [comment]
@MeghanLuecke and @beebouttw We did a first cut of the KMS platforms and only two of them are FedRAMPed (Huddle and Adobe Experience Manager) which is less than ideal. So we've reached out to a few of our internal FedRAMP experts to get the skinny and get more insights into what this means in reality.

**Comment by brandocalrissian** [comment]
I have more clarity after getting a refresher with one of the FedRAMP team members and am not worried about this as FedRAMP basically applies to platforms (multi-tenant instances) and not things like a KMS instance. Also have another FedRAMP contact in the same office who has a connection to Ops — sounds worthwhile to follow up on.

**Comment by matt-dobson** [comment]
That's good to hear. I think that qualification may have limited the proposed solutions.

If being FedRamped isn't a barrier is this an opportunity to take a broader look at possible solutions?

**Comment by brandocalrissian** [comment]
It's not as applicable of a limitation as we were thought from talking to our IA contacts. FedRAMP is relevant for the underlying cloud platform in our solution, not the application on top, since that's the part that's a shared resource. The Department is still responsible for the ATO evaluation above that stack (and, technically, for the ATO evaluation for that stack — FedRAMP is designed to help agencies with that shared evaluation).

**Comment by matt-dobson** [comment]
Do we know what impact the underlying cloud platform has on our choice of CMS/KMS?

**Comment by brandocalrissian** [comment]
@matt-dobson That'll be the "cloud ready" checkbox in the initial eval. There's still a chance we'll have to go on-prem for a solution, but we are looking to evaluate if a product is cloud ready for all the benefits to the Department of cloud deployments (and various department and government-wide directives).

**Comment by matt-dobson** [comment]
Great. I feel like that can really open up our options.

**Comment by MeghanLuecke** [comment]
This was extremely helpful - thanks all! I am particularly glad to hear FedRAMP isn't a deal-breaker at the CMS/KMS/application level given how many interesting candidates are not FedRAMP'd (but may be cloud-ready).

**Comment by MeghanLuecke** [comment]
Looking forward to the KMS eval demo today! Copying from Slack for team visibility: We're particularly eager to understand any updated criteria that emerged from your work on this issue (such as de-prioritizing the importance of being FedRAMP'd), and any other factors that have been added into your evaluation process. We'd also like to see the in-progress whittled down list of vendors, if any have been definitively cut under the updated criteria, and understand why. Then we'd like to set a timeline for producing the shorter list of "finalists" that merit deeper dives, demos, etc.

**Comment by karareinsel** [comment]
@MeghanLuecke #172 is slated for sprint Jordan which will be to refine and narrow the list of KMS contenders based on how well they support the mission critical user needs.
