### ISSUE TITLE
Content Strategist training/coaching kickoff with DOS

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#143]
As an 18F researcher, I want to kick off with the DOS Content Strategist team members to start laying the ground work, expectations, and finding opportunities to work on tangible projects so that we can start delivering value, training, and moving forward on the CS.

Resources:
Content Strategist Performance Profile
https://docs.google.com/document/u/2/d/1dH3EkogSd_wVGwVfaLKWKfBgV1Pk_KaDQKUA49m3AzY/edit#heading=h.yjfawycgpbn1

AC:
- [x] Level set on what a Content Strategy is, what the CS role is, future models beyond our tenure
- [x] Examine places we can start helping them, finding some tangible stuff we can work on with them
- [x] Get Ryan and Catherine in OUR github repo as collaborators
- [x] Develop as a content strategy system (because Catherine and Ryan are rotating out in the Summer)

Support:
@jeanninehunter 
@RyanSibley 
@yowill

**Comment by MeghanLuecke** [comment]
@durland18F Please make sure Meghan, Tyler, and Theresa also have access to the CS/CM repo as collaborators for backup coverage! Thanks!

**Comment by yowill** [comment]
We're trying to hunt down Ryan V.'s github user name to add him to the repo and close this out. His State Dept. doesn't turn up results when searching in Github. :(

**Comment by beebouttw** [comment]
Ryan V. has been unexpectedly absent most of this week with a cold, but I've reached out to him directly to see if he can relay his Github username to be attached to issues.  Hopefully I'll either have him back in the office tomorrow, or hear from him via email.

**Comment by MeghanLuecke** [comment]
@SwansonCL do you have any remaining questions on this issue? @yowill What are the steps on closing out this issue for today?

**Comment by yowill** [comment]
@MeghanLuecke  RyanV's account was shared and has been invited to the repo; I think we are good to close!
