### ISSUE TITLE
Align results to prioritize prototyping opportunities (product prioritization, content bucketing, and journey map)

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#145]
As an 18F researcher, I want to align the results from the [SOS product journey map,](#125 ) [product prioritization exercise](#123 ), and [content modeling to identify testing/prototyping opportunities](#133 ), the type of prototype best suited for the questions we're trying to answer (discrete functionality or more complex for example, paper vs. clickable), and priority of prototypes.

AC:

- [ ] Compile a list of potential prototype opportunities, what the testing method would be
- [ ] Rank them in priority order

Support: 
@vishaliyer-18f 
@matt-dobson 
@brandocalrissian 
@MeghanLuecke

**Comment by karareinsel** [comment]
The [product prioritization](#123 ) will identify the highest priority products for additional journey maps and it will prioritize the products that should be used for the content bucket labeling exercise.

**Comment by brandocalrissian** [comment]
Output from https://github.com/18F/dos-ops-center/issues/136 will also inform this issue.

**Comment by karareinsel** [comment]
@vishaliyer-18f @brandocalrissian @matt-dobson I created a s spreadsheet to track test ideas. Go ahead and start adding your test ideas to this spreadsheet and we'll review what's been added when we talk today at 3:30.
https://docs.google.com/spreadsheets/d/1HWnZWy8zR8p0jO7idkaRNhMnd5VDzbhhM-YDhBcmU0g/edit#gid=1016838690

**Comment by karareinsel** [comment]
Added user needs prioritization to the second tab which captures the most critical user needs based on Meghan and Tyler's assessment. Meghan and Tyler also shared Ops leadership mission critical needs and they are in ALL CAPS below.


**Mission critical user needs**
-I need to be able to create graphics and visuals (such as maps). **OPS LEADERSHIP**
-I need to be able to include source data with the content in a product.
-As a Watch officer, I need to share important information with CMS.
-I need to keep track of and be able to see in one place all of the information/data that is ingested and used to create Ops products. **OPS LEADERSHIP**
-I need to search and extract data/information from the KMS to comply with retention schedules
-I need to find information associated with a particular crisis or event
-I need to respect physical classification requirements
-I need to send time-sensitive alerts to mobile devices
-I need to be able to push content to a subscriber directly
-I need to be able to easily update existing information
-I need to be able to trust the information that I find - that it’s the most current and accurate

**Mission critical user needs that should be included in out of the box functionality in a KMS** (and therefore will not be a a focus of testing)

-I need to be able to edit a product at the same time with my colleagues - several of us need to be able to edit the product at the same time.
-I need to be able to identify and retrieve the most recent version of a piece of content
-I need to have roles with distinct capabilities and permissions.
-I need to link content to related content
-I need to be able to identify and retrieve the original sources for a content product
-I need a flexible tagging/metadata classification system to store/retrieve/disseminate content as per my content strategy
-I need to be able to preview content before it gets published
-I need to use version control for each piece of information/content
-I need to be able to review and approve content products

User stories for #178 and #169 are being updated to reflect the priority from Ops.
