### ISSUE TITLE
Investigate how to extract historical email data as a one-off or periodic process

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/dos-ops-center#146]
This is dealing with unclassified information only; classified information will have to be tackled separately in future.

There may be different answers depending on whether we're extracting data client-side or server-side.

This issue was part of #86 before being split out.

AC:
- [ ] Successfully extract ALDAC subfolder to prove we can do this

**Comment by beebouttw** [comment]
Bringing in Eric Johnson/Esmail Baerde/Pat Ligon from Exectech.

**Comment by beebouttw** [comment]
I spoke with Eric Johnson, he said the only concern is the content, not the process itself.  I identified a folder with no sensitive content, and compressed it into a .pst file.

**Comment by beebouttw** [comment]
File can be found in Github repo at https://github.com/18F/dos-ops-center/blob/master/18F%20ALDAC%20PST.pst
