### ISSUE TITLE
Digitize SOS Journey Map

### ISSUE THREAD

**Issue by matt-dobson** [18F/dos-ops-center#148]
Translate what we make on the whiteboard at the SOS journey mapping exercise into a shareable, editable digital format using Mural.

**Comment by karareinsel** [comment]
Hoping we'll be able to do this in real-time during the working sessions since we'll have two dedicated digital scribes.

**Comment by matt-dobson** [comment]
I think that will be a good accelerator but imagine we will still need time with it afterwards.

**Comment by karareinsel** [comment]
This was done in real-time during the working session so closing this issue.
