### ISSUE TITLE
Visually represent the results of the product prioritization working session

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#149]
As an 18F team member, I would like to visually represent the results of the product prioritization working session so that they can be shared with Ops Center leadership for them to review, react to, and use to inform decisions about their content products.

AC

- [x] Graph raw data results in the prioritization spreadsheet

Support:
@karareinsel 
@SwansonCL

**Comment by catherine** [comment]
👋hello from over at Turo. I think there is another Catherine that was intended to be notified 😉

**Comment by MeghanLuecke** [comment]
Tagged Catherine (SwansonCL) as a test.

**Comment by karareinsel** [comment]
I left Catherine tagged in the issue as support and removed her from the assignee field. The assignee field should have just the name of the lead person for the issue - people who are providing support are listed within the issue under "Support."

**Comment by MeghanLuecke** [comment]
Thanks. Yep, meant to remove her from assignees after confirming the test worked (given GitHub issues with mystery Catherine!)

**Comment by brandocalrissian** [comment]
Plotted the points on scatter plots, put in linear regression lines and calculated/ranked how far off each product's perceived impact is from the linear regression.

For both the CMS and the Watch there is a sheet in [the spreadsheet](https://docs.google.com/spreadsheets/d/1VMpcleX_MjT7gz0uHACAkTpxUQ5jqmeqTjZrKuOPDI0/edit) dedicated to
- the scatter plot
- the ranking of each product by LOI + LOE and deviation from the expected LOI given its LOE
- the results from our LOE/LOI sessions and the resulting raw numbers 

Some of the points in the scatter plots are for multiple products which causes the name of a product to be written over another. These products share the same LOE/LOI and regression values as can be found in the supplemental spreadsheets.
