### ISSUE TITLE
Get "The Guidance"

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#15]
As an 18F researcher, I would like to read the Ops Center "guidance" so that I understand their existing processes and procedures so that I can identify workflow improvements and possible features and functionality for a CMS. 

AC

- [ ] Request "guidance" from M&T

- [ ] Review "guidance"

**Comment by yowill** [comment]
@Beebouttw helped move this to OneNote recently and potentially share. It's about 250 entries compiled over decades. Notable: There's also a separate OneNote for task forces.

**Comment by beebouttw** [comment]
I am speaking to my front office today about the possibility of sharing this.  None of it is classified, but we might have to quickly scrub it for any sensitive information.  This is potentially an easy deliverable from our side.

**Comment by beebouttw** [comment]
Alright, Editor Guidance is added as a commit.  I'll close this, please feel free to reopen if there are further questions or if you need to see more.
