### ISSUE TITLE
Prep for the ExecSec Brief journey map working session (18F)

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#153]
As an 18F researcher, I need to prepare materials for the ExecSec Brief journey map working session so that all of the information related to the creation of the ExecSec Brief is captured during the session.

AC

- [x] Review the sample ExecSec Brief to become familiar with the product
- [x] Prepare the journey map template in Mural. Y axis is the steps (actions, feelings, users, stakeholders, technology, pain points). The X axis is the creation and distribution process (ingest, review, assemble & approve, distribute, store, and retrieve).
- [x] Prepare the agenda for the working session.
- [x] Prepare questions to be answered by the working session.

Support:
@beebouttw 
@RyanSibley 
@durland18F

**Comment by MeghanLuecke** [comment]
@matt-dobson let me know if I can help by setting up the journey map template in Mural (when you're ready to get this issue started) - if useful

**Comment by matt-dobson** [comment]
Mural template is here: https://app.mural.co/t/gsa6/m/gsa6/1551964816017/99d12f1389e6b9a337dfdf87af80b96d11a870cc

**Comment by matt-dobson** [comment]
Here is a work-in-progress list of questions related to the journey map exercise. Please feel free to edit or add questions: https://docs.google.com/document/d/1HYXVkff0XG8hucZeqT4VP6eDx-Am8oE6BsNJo71I9q8/edit?usp=sharing

**Comment by yowill** [comment]
@matt-dobson Is this finished for tomorrow?

**Comment by matt-dobson** [comment]
@yowill With this being virtual and essentially the same process as the SOS map I think this agenda will work: https://docs.google.com/document/d/1EL8M7abjpA8_5xmTApRxZLVobU2h-wTFX0QjvZBvxN4/edit?usp=sharing

Is there anything you'd like to add?
