### ISSUE TITLE
SOS Journey map synthesis and analysis 

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#157]
As an 18F researcher, I want to review the results of the SOS journey map so that I can be sure I've captured anything that was heard in the room that wasn't yet captured in the Mural notes.
AC:
- [x] Collaborate async (non destructively) to flag questions, gaps, unknowns **(USE COMMENTS IN MURAL!)**
- [x] Collaborate synchronously to discuss what we heard

Support
@durland18F

**Comment by MeghanLuecke** [comment]
@matt-dobson @durland18F Matt, Jeff, I am available most of 3/5 (other than 1-2pm) and would be glad to help push this one over the finish line - please let me know if you have outstanding questions or gaps for us!

**Comment by matt-dobson** [comment]
@MeghanLuecke That sounds great. I'll send a meeting request.

**Comment by MeghanLuecke** [comment]
@durland18F @matt-dobson @SwansonCL does this one look close to closeout? Let me know if I can assist in any way!

**Comment by matt-dobson** [comment]
@yowill It is enough for now.

**Comment by karareinsel** [comment]
One final request before closing this out - can a link to the mural be added here @matt-dobson ? Then I think this is ready to be closed.

**Comment by matt-dobson** [comment]
https://app.mural.co/t/gsa6/m/gsa6/1551192139165/f1daa5547193b64c19cbd4db8985b83ef3866721
