### ISSUE TITLE
Identify opportunity spaces for the SOS journey map 

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#158]
As an 18F researcher, I want to define the opportunity spaces coming out of the SOS journey map working session so that I can identify things to test and prototype in sprint Jordan.

AC:

- [ ] Identify where pain points/frustrations intersect with technology solutions to address potential features/functionality to test
- [ ] Identify where the content structure can be applied to the production of the SOS, in particular how the content structure and buckets can support the Ops Center ingesting content

Support:
@durland18F

**Comment by matt-dobson** [comment]
As we compare notes and examine journey maps for opportunities maybe we can begin considering a lightweight "Jobs to be Done" perspective when considering features and benefits?

![image.png](https://camo.githubusercontent.com/13ae97a60dc3b7a88425fc662af87a66ed77d89d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563333631383131396266613635353339636434326165622f38356236373365652d366462322d343534372d393935302d306461343434656230613764)

![image.png](https://camo.githubusercontent.com/52e22c94bff0d30327ed28053c4179304b2d67d1/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563333631383131396266613635353339636434326165622f66383236306662632d636132612d343434332d623536372d626132376634613234623535)

**Comment by karareinsel** [comment]
Moving to in progress based on conversations with Meghan. She said this work is already underway in the coworking sessions she and Catherine have done with Matt and Jeff.

**Comment by MeghanLuecke** [comment]
@matt-dobson @durland18F @SwansonCL From what I can tell from the SOS HMW work, it looks like the team is close to closing out the first AC for this issue. But I'm wondering if the second AC is actually a bigger issue - and broader than SOS. As of right now, we haven't done any thinking about how our current draft content buckets would intersect with information ingestion. It's a pretty big question and might even merit being a separate issue, since it goes far beyond the SOS process. But would be glad to know if that's what you meant with this specific AC!

**Comment by karareinsel** [comment]
@MeghanLuecke agree that content/data ingestion for SOS (or any Ops product for that matter) is a big question and is probably best addressed in a separate issue (or possibly multiple issues) for a future sprint. Ingestion of content has a large technical component that will be heavily influenced by the recommended KMS.

**Comment by matt-dobson** [comment]
@MeghanLuecke I think you're right - It may be easier to unpack in conversation.

I think we need a better cross-section of products to really answer these questions. 

I think this story needs hypotheses for those intersections and we can cross-check if those still seem valid with a wider set of products.

**Comment by karareinsel** [comment]
Issue #168 is for capturing the list of things to test coming out of the SOS journey map as a friendly reminder.

**Comment by yowill** [comment]
@matt-dobson Is this looking finished or close to finished?

**Comment by matt-dobson** [comment]
I think we can close it.

I think the general description is satisfied. I'm hoping the action items as they are written - identifying intersections between content strategy and technology - can be accomplished with our service blueprint exercise.

**Comment by karareinsel** [comment]
Are these the tests that are on lines 16-20 in the testing prioritization? 
https://docs.google.com/spreadsheets/d/1HWnZWy8zR8p0jO7idkaRNhMnd5VDzbhhM-YDhBcmU0g/edit#gid=0

**Comment by matt-dobson** [comment]
Those are related. The opportunities are captured in the "jobs to be done" and "how might we rows" of the journey map: https://app.mural.co/t/gsa6/m/gsa6/1551192139165/f1daa5547193b64c19cbd4db8985b83ef3866721

**Comment by karareinsel** [comment]
@matt-dobson can you add the opportunities to this issue for visibility/ease of sharing purposes? Thank you!

**Comment by matt-dobson** [comment]
Here they are. I think they make more sense in the context of the process - it is easy to see how they roll up to hypotheses and pain points: https://app.mural.co/t/gsa6/m/gsa6/1551192139165/f1daa5547193b64c19cbd4db8985b83ef3866721

How might we (HMW) allow the 2 sides of the house to share important information?
HMW know who is actually receiving the product And why they aren't getting it?
HMW be able to view formatting across devices and formats before sending?
HMW have visibility into the what the Watch is watching? (and vice versa)
HMW provide source data easily (where possible automatically)?
HMW make it easy to create meaningful graphics and visualizations?
HMW we have visibility into the work of other officers in CMS and the the Watch?
HMW know that our prioritization is meeting audience needs?
HMW track edits on low side such that changes made after flipping are consistent between low and high side?
HMW automatically include links to cables (and flip those links to the high side)?
HMW make sure that important information isn't missed?
HMW effectively present geographical and location data?&nbsp;
HMW make sure that the SOS product is comprehensive?
HMW ensure version control between drafting space and delivery space given final editing?
HMW make it easier to route info that is automatically included in SOS?
HMW Improve the quality of the information coming in?
HMW verify how and when sources have been checked?
HMW augment the ability of manual sorters to find relevant information?
HMW make guidance apparent throughout the draft and assembly process?
HMW get cables and other info into a shared space?

**Comment by matt-dobson** [comment]
@karareinsel @yowill Can we adjust the acceptance criteria? I think we've Identify opportunity spaces for the SOS. I think the service blueprint will help 1 and that 2 is bigger than the SOS.

**Comment by MeghanLuecke** [comment]
@matt-dobson That sounds like a good idea to me!

**Comment by karareinsel** [comment]
I translated the HMW's into user stories and added them to the KMS repo (there were a few non-functional user stories/requirements and I left those out). They are not yet categorized into swim lanes - will try to do that later today.

**Comment by karareinsel** [comment]
I think we're good to close this out @matt-dobson ?

**Comment by matt-dobson** [comment]
I'm good to close it.
