### ISSUE TITLE
Determine if Cloud PMO cloud is same as Cloud Shared Services is IRM cloud

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#161]
Split from #134.

**Comment by karareinsel** [comment]
@tadhg-ohiggins @brandocalrissian Based on our conversations with Kobe Gillette and Michelle Sparrow-Walker, I think we can close out this issue but let  me know if questions remain.

**Comment by yowill** [comment]
The boundaries of the Cloud is cloudy. They're all the same stuff.
