### ISSUE TITLE
Arrange Group Discussion with Obel "Kobe" Gillette

### ISSUE THREAD

**Issue by MeghanLuecke** [18F/dos-ops-center#162]
As an Ops PMIT (woohoo!), I want to better understand the IT and cloud landscape at State and make sure we have reached all the right players in order to decide whether to use State's in-house capacity to create a testing environment. 

AC:
Schedule interview with Kobe

**Comment by MeghanLuecke** [comment]
As of March 1, Kobe is still out of the office on paternity leave. Will revisit during Sprint Iran to see if we can move this forward, but it is currently blocked.

**Comment by brandocalrissian** [comment]
As of this morning, this seems to be scheduled for Friday, March 8.

**Comment by yowill** [comment]
DONE!

**Comment by MeghanLuecke** [comment]
GilletteOD@state.gov  - thanks!
