### ISSUE TITLE
Arrange Cloud Implementation Discussion with Alen Kirkorian

### ISSUE THREAD

**Issue by beebouttw** [18F/dos-ops-center#163]
As an Ops PMIT (woohoo!) I want to understand specifics for what the difference between "dev" and "production" environments on AWS and Azure entails.  I also want to see if information on pricing is available.  

AC:
- [ ]  Schedule interview with Alen Kirkorian.

**Comment by karareinsel** [comment]
Based on our conversations with Kobe Gillette and Michelle Sparrow-Walker on 3/8, I think we can close out this issue? @beebouttw @tadhg-ohiggins
