### ISSUE TITLE
Refine SOS Journey Map so that it captures roles and responsibilities

### ISSUE THREAD

**Issue by matt-dobson** [18F/dos-ops-center#164]
As an 18F researcher, I want to document the individual roles and responsibilities for key steps (we want to know the number of people and who they are) in the assembly of the SOS product so that we have an accurate enough representation of the assembly process.

AC
- [ ] Define the assembly process of the SOS for the key individual roles that directly contribute to the creation of the SOS.
- [ ] Add this information to the mural.
- [ ] Confirm accuracy of information with @MeghanLuecke and @beebouttw .

**Comment by yowill** [comment]
Has been filled out in follow up sessions, closing!
