### ISSUE TITLE
Analyze and Synthesize SOS Journey Map

### ISSUE THREAD

**Issue by matt-dobson** [18F/dos-ops-center#165]
Compare notes and examine journey maps for opportunities.

Maybe begin considering a lightweight "Jobs to be Done" perspective when considering features and benefits?

![image.png](https://images.zenhubusercontent.com/5c3618119bfa65539cd42aeb/85b673ee-6db2-4547-9950-0da444eb0a7d)

![image.png](https://images.zenhubusercontent.com/5c3618119bfa65539cd42aeb/f8260fbc-ca2a-4443-b567-ba27f4a24b55)

**Comment by karareinsel** [comment]
Closing out this issue because it's redundant with #158
