### ISSUE TITLE
Execute tests and experiments to validate solution hypotheses from #158 SOS Journey Map

### ISSUE THREAD

**Issue by matt-dobson** [18F/dos-ops-center#166]
As an 18F researcher, I want to identify and define the tests that I need in order to confirm which proposed KMS solutions and features would best answer and fit the needs of the Ops team when creating the SOS product.

AC:
- [ ] Do the actual series of experiments to test what is defined in #158 
- [ ] Record the results in real-time on the SOS Journey Map, KMS repo, in this issue, etc.

**Comment by karareinsel** [comment]
I think we can close out this issue since the tests should be captured under #145 . Each test that is identified will be tracked in its own issue. Let me know if I'm missing something.

**Comment by matt-dobson** [comment]
@karareinsel I think you're right. Seems duplicative.
