### ISSUE TITLE
Create a list of things to test coming out of the SOS Journey Map

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#168]
As an 18F researcher, I want to create a list of the things to test coming out of the SOS journey map, specifically things that should be tested as a result of identifying opportunity spaces  #158.

AC
- [x] Provide a list of tests 
- [x] The lists of tests will be used in #145 

Support
@durland18F 
@vishaliyer-18f

**Comment by karareinsel** [comment]
Please add tests to this spreadsheet https://docs.google.com/spreadsheets/d/1HWnZWy8zR8p0jO7idkaRNhMnd5VDzbhhM-YDhBcmU0g/edit#gid=1016838690

**Comment by karareinsel** [comment]
@matt-dobson can you include your list of tests for the SOS journey map in this issue for visibility and ease of information retrieval? Thank you!

**Comment by matt-dobson** [comment]
@karareinsel yes. I'm adding them. I don't think I'm actually advocating for testing all of them and multiple hypotheses could likely be (in)validated in a single test.

**Comment by yowill** [comment]
Hey @matt-dobson Are these added and ready for us to close this issue?
