### ISSUE TITLE
Validate LOI assessments with readers of CMS and Watch products

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#169]
As a member of this project team, I would like to validate the LOI assessments of the Watch and CMS products with the readers (or their proxies) of those products so I can confirm if they assign a different level of impact than we do so that we can ensure we have the most accurate product prioritization.

AC:
- [x] Identify readers/consumers of products (or their proxies) and the list of products they receive - Ops
** See Issue 175: Prepare plan for research questions and methods/exercises/tests, targeting midday Thursday 3/21 - 18F
- [x] Ops to review plan with Bob/leadership NLT OOB Friday 3/22 - Ops
- [x] Schedule the sessions (aim for less than 30 minutes, less than 15 if possible) for early the week of 3/25 if possible - Ops
- [x] Select and print recent samples of products - Ops
- [x] Dry-run of interviews internally based on 18F's plan - Ops
- [x] Do 2-3 sessions testing (5 as a stretch goal) - Ops, with 18F via phone?
- [x] Align results with the original LOI numbers and adjust product prioritization if needed, add the weighted LOI, update charts and graphs to inform testing and content strategy going forward, Ops team allocation planning (secondary item), document what worked, what didn't work with testing for this round - 18F (with input from Ops)

Support:
@durland18F 
@karareinsel 
@matt-dobson 
@MeghanLuecke 
@beebouttw 
@RyanV-State

**Comment by brandocalrissian** [comment]
Scheduling a time for interested parties to talk about this (from stand-up).

**Comment by MeghanLuecke** [comment]
Thanks Brandon - looking forward!

**Comment by brandocalrissian** [comment]
Initial discussion had and notes here: https://docs.google.com/document/d/1aWp9KxUOt7pssB3twSTnEHlmYZ-7FuOh6nef5bvB7Ug/edit#

**Comment by MeghanLuecke** [comment]
Thanks Brandon! After reviewing the next steps on the Ops side, I added some more detail to our AC so we can keep track. Let me know if any of the above doesn't look right on your end.

**Comment by brandocalrissian** [comment]
Current todo:

- write down the test plan script and the questions we're expecting to answer
- 18F discusses the test plan with Ops
- 18F run the test with Ops (test run), debrief *time permitting*
- Ops run the test with Ops (test run), debrief
- Ops run the test with Customers, debrief
- Document learnings

**Comment by karareinsel** [comment]
Calling this out for @matt-dobson @durland18F @brandocalrissian @MeghanLuecke @beebouttw @vishaliyer-18f . These are the LOI questions that we asked in the first round and they need to be asked in this around of testing so that the LOE/LOI data can be updated with the reader feedback.
*Timeliness* (customer urgency)

- Less than a day
- Within several days
- Highly variable - generally one week or more

*Reference value* (has a long shelf life)

- Years
- Less than a year
- Rarely referenced, time-bound content

*Request frequency*

- Regularly
- Intermittently
- Almost never

*Need for absolute accuracy*

- Must be absolutely accurate
- As accurate as possible

*Perception of value to Mahogany*

- High value
- Some value
- No value

*Perception of value to greater State Department*
- High value
- Some value
- No value

**Comment by brandocalrissian** [comment]
[LOI test protocol](https://drive.google.com/open?id=1OarS5EsRX2pLeX3MX7pEfIfp9MYggFggnikIjQcghA0) and [Highlighter content assessment exercise](https://drive.google.com/open?id=1ZusPrcAvmZBhuEYGbYK_-GfIA0JiBefTwxhAXX-7Rj4)

**Comment by beebouttw** [comment]
Today's 1200 ET LOI session will be

**Comment by brandocalrissian** [comment]
Reopening. Sessions are still happening, and the "visualization" hasn't started.
