### ISSUE TITLE
Request to M&T for High-Low side passover observation

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#17]
As a researcher, I want to observe the low to high side content flip so that I can understand the technical means for how content is flipped and why the content is flipped so that I can understand features and functionality that will be needed in the new CMS.

AC

- [x] Able to observe a Watch stander or CMS officer create content and flip it from the low side to the high side

**Comment by tadhg-ohiggins** [comment]
This will probably be done via observation of a tabletop scenario, since security issues would preclude doing it with real data.

**Comment by yowill** [comment]
Add Tyler and Meghan to the org! and then assign him to this. @hannahkane on it!

**Comment by yowill** [comment]
Complexity is dependent on if Tyler gets a Yes or No. :)
