### ISSUE TITLE
Set up Cloud.gov instance

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#171]
As an 18F engineer, I want to set up an instance of Cloud.gov on behalf of the Ops Center so that we have a sandbox that can be used for prototypes and testing features and functionality for a KMS solution.

AC
- [ ] Set up the Cloud.gov instance

**Comment by MeghanLuecke** [comment]
Hey @tadhg-ohiggins ! Do you have an estimate for how long this will take now that this is under way?

**Comment by tadhg-ohiggins** [comment]
I've confirmed that publicly-available URLs running arbitrary (but low in resource consumption) web applications can be set up in a basic cloud.gov sandbox.
