### ISSUE TITLE
Evaluation of KMS platforms still under consideration of critical user needs met by out-of-box functionality

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#172]
As an 18F researcher, I want to do a deeper analysis of the KMS platforms still under consideration (in the [KMS repo](https://github.com/18F/dos-ops-center-kms/issues/102#workspaces/dos-ops-center-kms-5c264892f9cceb5e65c195ee/boards?repos=163426891)) so that I whittle down the list to a few well-qualified candidates that best meet the most critical user needs for Ops and choose one that can serve as an illustrative example to demo of the testing needs, built in functionality, and pain points.

AC
- [x] Viability criteria for second round evaluation (this will include the mission critical user needs) - see comments below
- [x] Refine list based on the KMS candidates fit with criteria
- ~Identify best KMS candidate to demo~
- ~Set up demo~

Support
@karareinsel 
@tadhg-ohiggins

**Comment by brandocalrissian** [comment]
This is a follow-on to #173

**Comment by brandocalrissian** [comment]
Splitting demo bits in #182

**Comment by karareinsel** [comment]
Mission critical user needs below.
-I need to be able to create graphics and visuals (such as maps). OPS LEADERSHIP
-I need to be able to include source data with the content in a product.
-As a Watch officer, I need to share important information with CMS.
-I need to keep track of and be able to see in one place all of the information/data that is ingested and used to create Ops products. OPS LEADERSHIP
-I need to search and extract data/information from the KMS to comply with retention schedules
-I need to find information associated with a particular crisis or event
-I need to respect physical classification requirements
-I need to send time-sensitive alerts to mobile devices
-I need to be able to push content to a subscriber directly
-I need to be able to easily update existing information
-I need to be able to trust the information that I find - that it’s the most current and accurate

**Comment by karareinsel** [comment]
Mission critical user needs that should be included in out of the box functionality in a KMS (and therefore will not be a a focus of testing)

-I need to be able to edit a product at the same time with my colleagues - several of us need to be able to edit the product at the same time.
-I need to be able to identify and retrieve the most recent version of a piece of content
-I need to have roles with distinct capabilities and permissions.
-I need to link content to related content
-I need to be able to identify and retrieve the original sources for a content product
-I need a flexible tagging/metadata classification system to store/retrieve/disseminate content as per my content strategy
-I need to be able to preview content before it gets published
-I need to use version control for each piece of information/content
-I need to be able to review and approve content products

**Comment by brandocalrissian** [comment]
Per conversation yesterday, keeping this ticket as evaluating critical out-of-box functionality and splitting out other critical user needs as a separate ticket for next sprint.

**Comment by karareinsel** [comment]
Link to summary document https://docs.google.com/document/d/14kvJ0zFNxUVzg4gHIyIwAx52Jkn99kRrr6vVpb_HwXY/edit#
