### ISSUE TITLE
Collect examples of other content strategies to share and discuss with Ops team

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#174]
As a DOS team member, I want to understand what other organizations -- government to non government -- have done for their content strategies so that I can better understand the scope and what's possible for best practices on content strategies to help inform planning ours.

AC:
- [x] Collect examples from other 18F project content strategies (Any pieces such as but not limited to: Editorial calendars, metrics, governance, taxonomies strategies, guidance, etc.)
- [x] Collect examples of other government project content strategies (Any pieces such as but not limited to: Editorial calendars, metrics, governance, taxonomies strategies, guidance, etc.)
- [x] Collect examples of private sector content strategies (Any pieces such as but not limited to: Editorial calendars, metrics, governance, taxonomies strategies, guidance, etc.)
- [x] Place them in the partner shared Google Docs folder so that State can get familiar with the different approaches https://drive.google.com/drive/u/2/folders/1eVVz7UnRtMJLqMWPgRy996UgdftIiI5r

Support:
NO ONE

**Comment by vishaliyer-18f** [comment]
@MeghanLuecke This document has an index of all content strategy examples we've collected- https://docs.google.com/document/d/1g2gbXkGiNwkTaSgE261txMUmlQnx3XbOjDVCkjNZbic. There are some url's in there as well. 

We'll be happy to walk you through this next week!

**Comment by MeghanLuecke** [comment]
@durland18F and @karareinsel and @RyanV-State - what do you all think about moving the final AC for this into next week? I am eager to talk through these samples now and am reading them today, but on the other hand, I want to make sure Catherine can benefit from the discussion (she's out all week).

**Comment by karareinsel** [comment]
Since Catherine will be one of the content managers going forward, I think waiting until next week for the discussion makes sense.

**Comment by beebouttw** [comment]
Fair point -- would Will also want to be involved, or are you taking this over for him @vishaliyer-18f

**Comment by karareinsel** [comment]
Adding blocked tag - it can be removed once the final AC is complete next week.

**Comment by karareinsel** [comment]
Moved the last AC to it's own issue #202 so closing this issue.
