### ISSUE TITLE
Test future state service blueprint

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#177]
We believe that in order to make informed decisions about a future state Ops needs a comprehensive view of what is being proposed and how it will fit into their existing processes and workflow.

We can help them by mapping the current state and a hypothetical future state of the entire process and information flow. 

We'll know we're right if our partners and team and discuss future state of the project with consistent terms and shared understanding.

To (in)validate this hypothesis we can:

1. Share the hypothetical service blueprint with Ops Center users and test if this would meet their needs and identify gaps and opportunities. 

AC

- [ ] Prep service blueprint for testing, including a common definition for what a dashboard is and is not
- [x] Schedule testing sessions with Ops team members (1 Watch stander, 1 CMS officer)
- [x] Conduct tests
- [x] Define areas that are supported by the KMS and supported by adjacent tools to define the ecosystem

Support
@durland18F 
@vishaliyer-18f 
Catherine
@brandocalrissian

**Comment by yowill** [comment]
Linked and informed by #181 #180

**Comment by karareinsel** [comment]
The final version of the blueprint will likely be included in the market research report and/or the procurement package.

**Comment by MeghanLuecke** [comment]
@vishaliyer-18f @matt-dobson @SwansonCL @beebouttw is there a good time we could discuss "dashboard" definitions to inform the blueprint drafting process? We'll be coming back from a meeting during the cowork slot at 12 so that probably wont work, but I could do 1:30 or after.

**Comment by SwansonCL** [comment]
I am available this afternoon!

**Comment by MeghanLuecke** [comment]
@matt-dobson thanks again for the excellent blueprint discussion. What's the status of the AC for this issue? Are you still planning to do more structured "tests" or did we cover what you needed already? @brandocalrissian forgive me if I've missed it, but are you tackling that dashboard definition (embedded in the first AC for this issue)? Thanks all!

**Comment by matt-dobson** [comment]
@MeghanLuecke Yes. I think you're right. Those criteria are satisfied. I'll deliver the revised version later today. 

I think next steps are captured in issue #212 and other issues it will generate. I hope those issues will help influence and inform #217 and #213.

**Comment by karareinsel** [comment]
I'm going to close this issue and create a separate one to document the definition of a dashboard.
