### ISSUE TITLE
Data ingestion audit

### ISSUE THREAD

**Issue by MeghanLuecke** [18F/dos-ops-center#178]
As an Ops PM, I want to complete an audit of existing Ops data sources so that the results can inform plans for data ingestion and visualization in the new KMS, including evaluating out-of-the-box functionality versus customized dashboard options with KMS vendor contenders. 

AC: 

- [x] Build an audit of Ops data sources including the original/primary source and form of receipt in Ops (i.e. DSCC generates the info, then we get it as an email), current retrieval processes, prioritization of types of data, etc. 
- [x] Conduct an initial validation of the audit with 2 non-drafters in Ops (i.e. a quick sanity check with someone from CMS and someone from the Watch who did not actually develop the draft audit)

Support:
@brandocalrissian 
@beebouttw 
@tadhg-ohiggins 
@SwansonCL 
@karareinsel 
@MeghanLuecke

**Comment by MeghanLuecke** [comment]
Updated level of work estimate - it's not hard, but is time-consuming and requires comparing potentially different data uses on the Watch vice CMS. We may split this into two docs, but are not certain; identifying our many areas of overlap may be more valuable than splicing some of the differences.

**Comment by karareinsel** [comment]
Thank you for the update. One criteria that will be very helpful to know is if a data source exists on the low side, high side, or both.

**Comment by MeghanLuecke** [comment]
Thanks Kara that is crucial - I will make sure to add that to our draft tracker now before work starts.

**Comment by MeghanLuecke** [comment]
Draft tracker sent via email 3/20/2019. Will seek internal "validation" and also look for any 18F feedback on additional columns/details we should capture in the update.

**Comment by karareinsel** [comment]
@MeghanLuecke question about the audit and the "original source" column. It would be helpful to know how the original source collects the information that they share with you by email. Meaning, are they manually collecting the data and then emailing it to you? Or do they have a more automated data source that has rules in place to email the data to you? I'm trying to figure out if it's possible to hook into their original source (via something like an API).
