### ISSUE TITLE
General Alerts journey map session

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#181]
As Ops Center and 18F team members, we want to create the journey map for the General Alert product so that we can identify critical pain points and mission critical user needs that will inform the KMS selection.

Ops has offered to do some work upfront to prepare parts of the journey map in order to facilitate the process and expedite learning/action.

AC
- [ ] Do the journey map session

(This is an issue to execute the session only, moving the analysis to Sprint Iran) 

Support:
@SwansonCL 
@durland18F 
@matt-dobson

**Comment by yowill** [comment]
Scheduled or Thursday at Noon during Content co-working time! (Use that standup and call in info)

**Comment by beebouttw** [comment]
Scheduled for Wednesday 3/13 @ 1500ET
