### ISSUE TITLE
Stand up a KMS Drupal demo platform

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#182]
As a researcher, I need a KMS Drupal platform at my fingertips so I can
- demonstrate a tangible example of what is available out of the box for a common KMS to support and augment discussions
- have a customizable KMS available for performing tests for the content strategy and KMS needs 

This is *absolutely not* choosing a recommended KMS. For this issue, we will select a common KMS platform based primarily on its relative ease for us to stand up. We are minimizing the lead time to a demo platform.

AC:
- [x] use a web browser to log into a KMS platform we control and have full rights to customize
- [x] see a piece of content produced by the KMS platform (Hello, world!)

**Comment by brandocalrissian** [comment]
This will likely be a follow-on to #171

**Comment by karareinsel** [comment]
Adding the blocked tag - standing up the Drupal instance has taken longer than expected and will be wrapped up in early sprint Kosovo. The blocked tag will be removed once the instance is up and running - we'll plan to do a walk-thru with Meghan and Tyler.

**Comment by MeghanLuecke** [comment]
@tadhg-ohiggins hope you are feeling better! When you're back, would it work to do a Drupal pre-demo Weds the 10th, perhaps at 3pm ET?

**Comment by tadhg-ohiggins** [comment]
@MeghanLuecke That should work.

**Comment by MeghanLuecke** [comment]
@tadhg-ohiggins where does this issue stand? Are there elements of the AC still in progress?

**Comment by karareinsel** [comment]
@tadhg-ohiggins since both AC are checked off, I'm assuming this issue is done and can be closed. If I'm incorrect, please re-open and/or create a new issue to address the remaining AC that still need to be resolved.
