### ISSUE TITLE
Validate impact of media usage in Ops readers' perceptions of impact of Ops products

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#185]
As an 18F researcher, I want to validate if including different forms of media in a sample Ops product influences Mahogany's perception of the impact/value of that product so that I can recommend the best type of media for Ops to use in their products.

AC

- [ ] Identify a CMS product and a Watch product that currently don't use media but there's a desire for them to use media
- [ ] Mock up multiple versions that include a different form of media - one with a photo, one with a map, one with a graph/chart
- [ ] Show each version one at a time to a user (someone who receives Ops products) to get their assessment of value to see if the inclusion of different types of media influences how they perceive the impact of that media
- [ ] Bob bite - recommended forms of media that drive the most impact for Mahogany (aka their prime readers)

This test could be done in person (on paper) or it could be done remotely via a screenshare and can be done in conjunction with #169 .

**Comment by matt-dobson** [comment]
@karareinsel - This lines up directly with some of the hypotheses from the journey maps. Here's how we were thinking about approaching research on this:

We believe CMS Officers have a problem creating effective custom maps to communicate with their audience.

We can help them add information to maps with visual mark-up and other tools.

We'll know we're right if their audience can easily comprehend and act on the information.

To (in)validate this hypothesis we can:

1. Identify real-world scenarios where a custom map view would enhance communication. (Examples might include evacuation plans, or directions to shelter, or airports.)
2. Create visuals to communicate the scenarios to the audience.
3. Test audiences comprehension of the visual and associated written information.


Similarly, We believe CMS Officers have a problem creating effective data visualizations to communicate with their audience.

We can help them by providing data visualization tools that integrate with their workflow.

We'll know we're right if their audience can easily comprehend and act on the information.


To (in)validate this hypothesis we can follow the same process:

1. Identify real-world scenarios where a data visualization graphic would enhance communication.
2. Create visuals to communicate the scenarios to the audience.
3. Test audiences comprehension of the visual and associated written information.

If we determine that the visual information makes the communication more quickly and easily understood we will then need to explore the creation of the visual information.

If we determine that the visual information makes communication of the data  quicker and easier we will then need to explore the creation of the visual information.

**Comment by karareinsel** [comment]
@matt-dobson I think there might be an intermediary step between the AC and what you've written and that is identifying tools that can support map or data visualization creation (and thus a different github issue). I'd add to your process is having Ops users test creating a map or visual using those tools - that may be in implicit in your hypotheses, I just wanted to call it out.

**Comment by brandocalrissian** [comment]
From today's meeting: Meghan's looping in Luke (in CMS) who did some work about the kinds of maps they'd like to use— this list could act as a baseline hypotheses to test.
