### ISSUE TITLE
Develop list of mission critical technical needs for a KMS

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#187]
As an 18F researcher, I would like a list of the mission critical technical needs for a KMS platform that can be used to evaluate the KMS that remain in the KMS Under Consideration swim lane (in the KMS repo) so that I can apply those criteria to whittle down the list to a select group of KMS candidates for final evaluation and testing.

AC:
- [x] Develop list of mission technical needs for Ops that a KMS will need to support

Support:
@karareinsel 
@tadhg-ohiggins

**Comment by brandocalrissian** [comment]
- Needs to interface with the low/high side flip bridge or equivalent
- Needs low to high content replication that works through the low/high side bridge flip mechanism.
- Need to create content on the high side that embeds potentially nested content replicated from the low side.
- Needs to work with continuous deployment.
- Needs to parse email headers and associated metadata.
- Needs to parse email chains and associated metadata.
- Needs to interface with cables as a data source (low and high).
- Needs to interface with Infoviewer as a data source.
- Needs to interface with Dataminr as a data source.
- Needs to be able to automatically pull metadata from cables and apply relevant KMS tags.
- Needs to support embedding URLs from public sources (video, photos, live video feeds, imagery...) within content.
- Needs to support embedding content from any managed data source into content products (cables, other content products, …)
- Needs to match or exceed NARA records export capabilities of current systems.
- Needs to allow tracking of content as record types and edit dates to comply with retention schedules.
- Needs to interface with email for delivery of content products to content consumers.
- Needs to interface with SMS for delivery of content as push messages to content consumers.
- Needs to control distribution of content to particular content consumers or groups of users where users may subscribe to multiple channels (email, SMS, portal, phone, …)
- Needs to allow content consumers to manage what content they receive and through what channel (email, SMS, portal, phone, …)
- Needs to be performant enough to meet Ops needs for timeliness (measured in seconds, not minutes).
- Needs to support content creation by non-Ops users.

**Comment by brandocalrissian** [comment]
These came out of the users needs on the KMS board. I grouped the needs and thought about how they would be expressed as technical needs. Some of the KMS board needs that might affect technical needs are already expressed in the evaluation we're doing in #172 so they are not included.

For transparency, these were the KMS board needs considered:
```
Content on the High side should include content originating from the Low side. #48
Need to respect physical classification requirements #77
I need to track classification levels for content nested within other content #65

I need to be able to do continuous deployments #30

What's it like to get information out of Email? #90
I need to extract information out of an email or email chain#62
What information should flow from Infoviewer to the KMS? How does that work? #100
Need to be able to find and read cables in the KMS system #78
Need cables to be automatically tagged to ensure proper distribution and awareness #79

I need to embed content from publicly available sources (video, photos, live video feeds, imagery...) #72
I need to automatically populate/include links to cables. #145
I need to be able to identify and retrieve the original sources for a content product #83

I need to comply with NARA records requirements #95
I need to search and extract data/information from the KMS to comply with retention schedules #96

I need to be able to push content to a subscriber directly #33
I need to push specific content to specific groups of people #82
I need to be able to push out notifications via SMS #122
I need to send time-sensitive alerts to mobile devices #70
I need to be able to publish content to a portal #32
I need to be able to subscribe to and unsubscribe from content products #39

I need to be alerted when a product is ready for review #7
I need to be able to review and approve content products #6
I need to be able to easily share information from Post with the Ops Center, even without them asking for it #41
I need to collaborate and exchange information with partner agencies #85
As a Watch officer, I need to share important information with CMS. #136
As a CMS officer, I need to share important information with the Watch. #137
I need to have visibility into the work my fellow CMS officers are doing. #142
I need to have visibility into the work my fellow Watch officers are doing. #143

I need to be able to easily create content and not have to reinvent the wheel every single time #8

I need Ops to give me information as quickly as possible, even it’s potentially inaccurate, when human lives are at stake. I’ll take speed over accuracy. #49
I need to send time-sensitive alerts to mobile devices #70

I need to be able to see metrics/analytics related to support Ops provided to a given embassy. #147

I need to be able to trust the information that I find - that it’s the most current and accurate #3
```
