### ISSUE TITLE
Evaluate mapping needs for use by Ops

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#188]
We believe that the Ops team has difficulty creating effective custom maps to communicate with their audience.

We can help them by identifying tools (or features of tools) that enable them to easily create and visual mark-ups.

We'll know we're right if they can easily create maps and location based visuals.

To (in)validate this hypothesis we can:

1. Identify real-world scenarios where location based visuals would enhance communication. (Examples might include evacuation plans, or directions to shelter, or airports)
2. Evaluate different visual communication tools that would help Ops more effectively communicate
3. Ensure that our recommendations work for the Ops team considering available time, resources and skills. 

AC

- [x] Talk with 2-4 Ops users to dive deeper into their needs and identify common scenarios 
- [x] Research various mapping tools
- [ ] Create market research doc to share with Ops team

**Comment by MeghanLuecke** [comment]
@karareinsel I was unable to drag this into "In Progress" - but I know Vishal just spoke with Luke. I'd also like to recommend that we pare down the first AC - Luke has worked with both the Watch and CMS, so we're inclined to move forward with this issue and not conduct further user research within Ops. We'd really benefit from seeing 18F's research on a range of existing mapping tools in order to move forward. @vishaliyer-18f and the team, if you have any remaining specific questions about user scenarios for maps that are necessary to resolve before doing tools research, please let me know and I'd be happy to chat this afternoon!

**Comment by vishaliyer-18f** [comment]
Updated the story for this to be more of a market research document.

**Comment by MeghanLuecke** [comment]
Thank you Vishal! Sounds great.

**Comment by MeghanLuecke** [comment]
@vishaliyer-18f we plan to share the initial market research on this with our colleagues at our leadership meeting tomorrow midday - if useful, perhaps we could touch base briefly before then to coordinate how we should present your work?

**Comment by vishaliyer-18f** [comment]
@MeghanLuecke, sounds good. I'll share a draft with you today afternoon. We can maybe chat once you have chance to look at it?

**Comment by karareinsel** [comment]
@vishaliyer-18f we have a regular meeting with @MeghanLuecke and @beebouttw at 1:30 today if you want to use that time to chat about the draft?

**Comment by vishaliyer-18f** [comment]
Draft document- https://docs.google.com/document/d/1S4egmXtJcrgh7nvtlW6G-4Wi1QCWVWnUhweSP49oc6I

Talk soon!

**Comment by MeghanLuecke** [comment]
Thanks @vishaliyer-18f - can you provide us access? I got the classic "access denied" when I tried the link!

**Comment by vishaliyer-18f** [comment]
Try this link- https://docs.google.com/document/d/15sucv77n_jHiaK80OlabmSOrzhmRbUxLX5hZ7Z8mPSY

**Comment by beebouttw** [comment]
Got access.  Looks fantastic!  Great job, guys.

**Comment by vishaliyer-18f** [comment]
@MeghanLuecke, pricing info added for ArcGIS & Maps4news. Keep in mind these are "starting from" prices. Factors like # of licenses, level of customization etc will make them higher.

I also moved Mapbox to the platform as a service section. I was on the fence with that right from the beginning, but looking at the pricing convinced me that it was really that.
