### ISSUE TITLE
Create quick-look representation of the current state of KMS evaluation

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#189]
As a team member or executive sponsor, I would like to quickly see the current state of the KMS evaluation so I can have an idea what we have considered and where we are in the process.

Essentially, package up the output from #140.

Could be a short prose document, could be an evaluation matrix. Could be both.

**Comment by brandocalrissian** [comment]
The first draft of the document is here: https://drive.google.com/open?id=1p34nrisy5pLNa3_h4OrA8HSUr57qwzbU9ja1NZfjDps

Comments, questions, concerns are all welcome, @MeghanLuecke and team!

The backing spreadsheet with the data is here: https://drive.google.com/open?id=1oAJY_dylsTBHTT6ODvKBI8GN_5kkrzIm-nVvPORof_8

I expect we'll need to flip axes in the chart as we get more criteria in the evaluation; will worry about that when writing up the results for the next round.

**Comment by brandocalrissian** [comment]
Keeping this ticket open during Ops review and any resulting revisions.

**Comment by MeghanLuecke** [comment]
Thanks Brandon! Will take a look.

**Comment by brandocalrissian** [comment]
Rolled changes from feedback into [the doc](https://docs.google.com/document/d/1p34nrisy5pLNa3_h4OrA8HSUr57qwzbU9ja1NZfjDps/edit). Closing ticket.
