### ISSUE TITLE
Confirm KMS evaluation criteria with Ops leadership

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#192]
As 18F team members, we want to share the KMS evaluation criteria (mission critical user and technical needs) with Ops leadership to capture any other criteria that is important to them to be included as we evaluate KMS options.

AC
- [x] Share list of mission critical user technical and technical needs with Ops Leadership.
- [x] Schedule a discussion (if needed) to confirm if any criteria are missing.

Support
@brandocalrissian 
@karareinsel

**Comment by MeghanLuecke** [comment]
For the week of April 1, Tyler and Meghan will provide a high-level update for Bob to let him know how many demos have been done and any new considerations those demos have revealed (though will not yet brief on specific tools unless needed). Then, we will have a more lengthy discussion of criteria (for issue 192) and KMS evaluation status overall the following week.
