### ISSUE TITLE
Confirm current records retention process with ExecTech

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#193]
As an 18F researcher, I need to know what the current records retention process is for OneNote and SharePoint for Ops so that I can confirm if the new KMS under consideration can provide the same support . 

AC

- [x] Talk to ExecTech to confirm current solution - are hooks built into OneNote and SharePoint or is the data exported on a regular, automatic basis?
- [x] Add to #187 

Support
@beebouttw 
@RyanV-State

**Comment by MeghanLuecke** [comment]
Thanks Kara! Tyler also has some ideas on this one and we may kick it off via an email chain to start. We can go over next steps during backlog grooming!

**Comment by karareinsel** [comment]
@beebouttw - Any word from ExecTech?

**Comment by beebouttw** [comment]
@karareinsel Nothing yet.  i reached out to Tom Lawrence Monday, but he appears to be offline for 5 days, so he must be out of the office.  I'll speak with one of his deputies today.

**Comment by beebouttw** [comment]
Alright, official word from ExecTech -- OneNote pushes a copy of all data out for NARA retention via an API hook in O365.  SharePoint does the same, but as most SharePoint is currently on-prem they're not yet using the O365 method.  Any solution we implement would need an API to export data, but it would not necessarily need to categorize or pre-sort that data.  So long as we have a copy for records, we're in the clear.
