### ISSUE TITLE
Drupal demo site walk-through with Meghan and Tyler

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#198]
As an 18F researcher, I would like to walk @MeghanLuecke and @beebouttw through the Drupal demo site so that we can whittle down what would be the most useful features to demo to Bob and Ops leadership.

AC

- [ ] Develop list of useful list of features/functionality (pro's and con's, pending questions)
- [x] Schedule a date and time for the walk-through

Support
@stvnrlly

**Comment by karareinsel** [comment]
@tadhg-ohiggins @MeghanLuecke said that April 12 looks good on their end to do a walk-thru - does that work for you?

**Comment by MeghanLuecke** [comment]
@tadhg-ohiggins , for the first AC in this issue, was just talking with @beebouttw about key features that are still up in the air. The most important one we've not yet discussed is subscription services. Is that something we could prototype in Drupal to understand options? 
Separately, prototyping and playing with content tagging and search would be very helpful - is that something we could prototype within the Drupal instance?

**Comment by MeghanLuecke** [comment]
@karareinsel , @tadhg-ohiggins and @stvnrlly  - here is a list of features we may need to test further with Drupal, OR which we could resolve through a follow-up discussion if you already have the answers: 
1) Collaborative editing - Tadhg is exploring EtherPad and OneNote API
2) Content tagging and search - could we prototype this in your Drupal instance? Is there another way to better understand Drupal's (and Wordpress and Joomla's) capabilities on that front? 
3) Subscription services - we need to understand the options for building this in Drupal or other open-source options. 

I'll build this list into a story for the next sprint. Closing this issue but will continue to seek your input and feedback on the list going forward!

**Comment by karareinsel** [comment]
@MeghanLuecke - to confirm, are you creating the story for sprint Liechtenstein (which starts today) or for sprint Moldova (which starts April 29)?
