### ISSUE TITLE
Evaluation of KMS platforms still under consideration of mission critical user needs (not out-of-box)

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#201]
Mission critical user needs below.
-I need to be able to create graphics and visuals (such as maps). OPS LEADERSHIP
-I need to be able to include source data with the content in a product.
-As a Watch officer, I need to share important information with CMS.
-I need to keep track of and be able to see in one place all of the information/data that is ingested and used to create Ops products. OPS LEADERSHIP
-I need to search and extract data/information from the KMS to comply with retention schedules
-I need to find information associated with a particular crisis or event
-I need to respect physical classification requirements
-I need to send time-sensitive alerts to mobile devices
-I need to be able to push content to a subscriber directly
-I need to be able to easily update existing information
-I need to be able to trust the information that I find - that it’s the most current and accurate

Split of #172 

Support
@karareinsel 
@tadhg-ohiggins 
@MeghanLuecke 
@beebouttw

**Comment by brandocalrissian** [comment]
We have turned these user needs into things to look at in the KMS evaluation here: https://docs.google.com/document/d/1SukpvTbatt9Dg8GpV_60yOJdwHENIBppM_95liWo_eU/edit#

**Comment by brandocalrissian** [comment]
We will populate a [sheet in the KMS Eval Worksheet](https://docs.google.com/spreadsheets/d/1oAJY_dylsTBHTT6ODvKBI8GN_5kkrzIm-nVvPORof_8/edit#gid=1400400590) with the notes we're taking for this ticket's KMS evaluation.

**Comment by karareinsel** [comment]
@brandocalrissian information from AEM. 
"AEM Sites, which is what DS Daily uses, is great for publishing web content and works in an author/publish model where a small group of authors publish to the site.  However, the need for simultaneous editing of an online document, which was raised during the call, is more of a Google Doc, Box, etc. functionality. Assuming the ability for visitors to subscribe to content is also part of the business need, that too is not supported by our CMS. "

**Comment by brandocalrissian** [comment]
Split out the criteria carried over from Kosovo into #223.
