### ISSUE TITLE
Debrief Ops team on content strategy examples

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#202]
As an 18F team member, I would like to brief the Ops team on the sample content strategies that were shared as part of #174.
- [x] Find time to discuss with Ops team about what looks interesting, is standard vs unique, what to look for and think about when crafting ours
- [ ] Complete a draft list of content strategy next steps for the Ops context based on lessons from samples (i.e. do we want to prioritize documenting and validating our current editorial calendar in the next sprint? etc).

Support
@SwansonCL

**Comment by MeghanLuecke** [comment]
@durland18F when's a good time to schedule this? I'd like to get this on the calendar before the days fill up!

**Comment by karareinsel** [comment]
@durland18F are we good to close out this issue or is the 2nd AC still in progress?

**Comment by durland18F** [comment]
We certainly have a draft in progress, so I think we can close it.
