### ISSUE TITLE
Oxcyon Centralpoint demo

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#203]
As 18F and Ops Center team members, I want to see a demo of the Oxcyon Centralpoint KMS so that I can see the product in action, ask questions, and evaluate if Centralpoint is the right fit for Ops needs.

AC

- [x] Create questions for the demo
- [ ] Post-demo, add notes (including pro's and con's of the product) to the notes doc

**Comment by karareinsel** [comment]
Link to demo questions https://docs.google.com/document/d/1tYycuGRF4MdjqHyAzu1bzovMP2iOZaanqN7SjJ-QyFc/edit

**Comment by karareinsel** [comment]
Demo is scheduled for Wednesday, April 3, 1:00 - 2:00 ET. James Venus is the rep.
Please join my meeting from your computer, tablet or smartphone.
https://global.gotomeeting.com/join/476518493


You can also dial in using your phone.
(For supported devices, tap a one-touch number below to join instantly.)

United States: +1 (646) 749-3112
- One-touch: tel:+16467493112,,476518493#<tel:+16467493112,,476518493>

Access Code: 476-518-493

**Comment by karareinsel** [comment]
Questions sent to Oxycon (4/2).

**Comment by karareinsel** [comment]
Below are Oxcyon's answers to our questions. Their answers are in *bold*.

- What is the typical amount of data (aggregate volume, transaction frequency) that your customers using this/similar products deal with? *The typical amount of data always varies per client and also does the transaction frequency*. 

- What’s the largest amount of data any of your customers deal with? *Over 285 million records*.
- How does your product support working in a secure/classified environment? *Centralpoint can be supported in a complete secure / classified environment for example hosted on-premise currently at The United States House of Representative Intelligence Committee*
- How does your product support collaborative editing--can two people work on the same document at the same time? *Centralpoint recommends pessimistic locking (this is when you lock the record for your exclusive use until you have finished with it. It has much better integrity than optimistic locking. Please note that every client is different and you might have your own requirement for this feature*.

- Do you have a cloud instance and installed instance? *Yes Centralpoint supports on-premise, cloud and installed instance*. 
- Can they communicate/can content be replicated across the two instances? *Yes*
- Have you done this for existing clients? *Yes*
- Does your product support integration with Outlook?  *Yes*
- Can products created in your Knowledge Management System (KMS) KMS be published/distributed through Outlook? *Yes*
- If so, how does the integration work?
Inbound? *Yes and via web service*
Outbound? *Yes and via web service*
- Does email metadata (Subject, sender, etc.) travel into your system? *Centralpoint can consume any metadata into Centralpoint*
- Can metadata be attached to in-bound data via rules (e.g. could an email from a particular account or with a particular term in the subject line always carry a particular piece of metadata)? *Yes*
-Can your system automatically create a document of a given content type based on a selected piece of incoming data? *Yes Centralpoint can scan and glean your content to automatically apply metadata and taxonomy to your incoming data imported or indexed into Centralpoint*.
- What other mechanisms or APIs does your product have for ingesting content? *Yes Centralpoint can import from any source as long as we have access to the data*. 
- From what kind of sources? *Centralpoint can schedule the pick-up and or data transfer of content from any source such as (file path, database connection or etc.)*
- How are these configured? *Centralpoint allows you to schedule the pick-up and or data transfer of content from any source such as (file path, database connection or etc.)*
- How does your product support export of data and changes to data for record retention purposes? *Centralpoint allows you to export data directly with the ability to make changes to data and or record retention and can be configured by the client*.
- How does your product support exporting of live content/data to dashboard products? *Centralpoint supports exporting of live content and data through our Centralpoint Dashboards*.
- How does your product support users subscribing to specific content products created in the KMS? *Centralpoint support content types which allow you to filter the content down to the audience and the specific role of the user*. 
- Do you have functionality that supports users managing their subscriptions (frequency, format, topics)? *Yes*
- If so, how are subscriptions published and distributed (Email, RSS, SMS, Portal?) *Can be published and distributed to all the above*.
- How does your product facilitate search of managed content managed? *Content can be searched and managed down to the role of the user and with Centralpoint Global login we can hook directly into the following: Centralpoint supports the following sources: Centralpoint | Active Directory (LDAP) | OAuth & OpenID | SAML 2.0 (Symantec, Okta, Ping Identity) | Quickfill | NEA | Custom)*.
- How does your product facilitate traceability of nested content? *Centralpoint can facilitate this we track everything that the user is doing and provides the content to be nested within nodes*.
- What parts of the product can be customized? *Centralpoint can be fully customized and is one of the reason Centralpoint is updated every 2 week*. 
- To what degree? *Any degree and we do offer the Source Code*
- Can customers make these customizations themselves or do they have to go through your support team? *Oxcyon provides complete training and knowledge to our clients so you can support these customization on your end or if you would like our support team to manage this we can provide this as well*.

**Comment by matt-dobson** [comment]
I'm always concerned when I see a user interface that seems neglected and outdated. It makes me wonder if the user experience is also not prioritized. Beyond any concern for aesthetics, the interactions seemed complicated, slow, and clumsy. There seemed to be some significant friction for the user — if the salesperson can't do a task quickly I imagine it is worse for the customer. 

The lack of a collaborative editing environment and general disdain towards the idea seems like a bad sign. I think great software can be opinionated in it's approach but should be tuned into user needs. The salesperson didn't seem to reflect that user-centered perspective regarding this feature and workflow.

**Comment by brandocalrissian** [comment]
Demo completed. Closing ticket.
