### ISSUE TITLE
Adobe Experience Manager demo

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#204]
As 18F and Ops Center team members, I want to see a demo of Adobe Experience Manager KMS so that I can see the product in action, ask questions, and evaluate if AEM is the right fit for Ops needs.

AC

- [x] Create questions for the demo
- [ ] Post-demo, add notes (including pro's and con's of the product) to the Adobe Experience Manager card in the KMS repo

**Comment by karareinsel** [comment]
Link to demo questions https://docs.google.com/document/d/1tYycuGRF4MdjqHyAzu1bzovMP2iOZaanqN7SjJ-QyFc/edit

**Comment by karareinsel** [comment]
Questions sent to AEM (4/2).

**Comment by yowill** [comment]
We had the meeting with them, but the Communities tool is not going to be supported anymore so they wanted to prepare a demo for their Sites tool, so we'll need to reschedule this. Marking as blocked due to their issue.
