### ISSUE TITLE
Huddle demo

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#205]
As 18F and Ops Center team members, I want to see a demo of the Huddle KMS so that I can see the product in action, ask questions, and evaluate if Huddle is the right fit for Ops needs.

AC

- [x] Create questions for the demo
- [ ] Post-demo, add notes (including pro's and con's of the product) to the Huddle card in the KMS repo

**Comment by karareinsel** [comment]
Link to demo questions https://docs.google.com/document/d/1tYycuGRF4MdjqHyAzu1bzovMP2iOZaanqN7SjJ-QyFc/edit

**Comment by karareinsel** [comment]
Scheduled for Friday, April 5, 11:00- 12:00 ET
Zoom Link:

https://huddle.zoom.us/my/jspinelli

**Comment by karareinsel** [comment]
Questions sent to Huddle (4/2).

**Comment by brandocalrissian** [comment]
Demo completed.
