### ISSUE TITLE
Mapping tools evaluation

### ISSUE THREAD

**Issue by vishaliyer-18f** [18F/dos-ops-center#207]
We believe that the Ops team has difficulty creating effective custom maps to communicate with their audience. We conducted an initial round of user needs assessment and created a market report based on that (#188) in which we narrowed down a few options that we'd like to evaluate further.

AC

- [x]  Create test accounts with Maps4News and ArcGIS online and explore features
- [x]  Schedule demos for Maps4News
- [x]  Document findings and determine a path forward for conducting trial runs with Ops, including identifying sample products that would benefit from using this map tool on a trial basis.
- [x]  Reconcile findings with work in #208, which may overlap.

Support
@beebouttw 
@MeghanLuecke 
Luke Meinzen

**Comment by MeghanLuecke** [comment]
Hey @vishaliyer-18f - were you still pursuing access to ArcGIS Online for a test run, as well as Tableau Maps? If not, let's figure out how we can keep this issue moving otherwise. I'd like to work with the team here to try out Maps4news to create some of the specific map needs Luke identified, but I don't want to do that with just one tool - we'd like to compare. Thanks! Adding @beebouttw as well

**Comment by vishaliyer-18f** [comment]
I contacted ArcGIS for a demo and they sent me to a team in GSA that works on our implementation of the software. And based on your standup message, looks like State has it too. I spoke to the GSA contact this morning and similarly got the sense that its likely too much for your needs. Also, they weren't sure its intended to be used in a static way (you can always take a screenshot, but that can only go so far).

ArcGIS also has an offering focused on storytelling- http://storymaps.arcgis.com/en/. It looks great, but the outputs are basically web pages. I agree that having another point of comparison is useful. I recommend doing a demo with the State dept installation of the software, rather than GSA's (but I can do that if needed). 

Can you let me know who would you like to work on trying out the tools? I'll coordinate with them.

Tableau was not under consideration for this story- the assumption was that lacking the large scale data its good at, its utility would be limited. Let me know if you'd like to pursue that too, we can add it to the mix easily since you have access to it.

**Comment by MeghanLuecke** [comment]
Thanks @vishaliyer-18f  - I thought we were going to look exclusively at ArcGIS Online, not the desktop ArcGIS? Does one automatically have access to both if you have the desktop instance? If not, could you request a test account specifically with ArcGIS Online? 

On Tableau Maps, I think we should definitely try it out JUST because our colleagues have it already. If we get into it and immediately find it requires large scale data even for basic mapping, we can scrap it.

**Comment by vishaliyer-18f** [comment]
When I said ArcGIS, I did mean the online version. But yeah, looks like at least GSA has access to both, I wouldn't be surprised if that's the case for State as well.

For the test accounts, its a little bit of a chicken and an egg situation since we need to know the email addresses to create them (FYI- I was also planning to do trial runs this week, so we'll have that at least).

Here's where we are with them-
1. Maps4News: Already created
2. ArcGIS: I can create test accounts using GSA's instance anytime now
3. Tableau: You will have to do this since its a State instant (I would like an account too, if possible)

**Comment by vishaliyer-18f** [comment]
@MeghanLuecke, I also think that the Ops folks can do this at their own pace. Doesn't have to be at a defined time, so let me know who would like to do this!

**Comment by vishaliyer-18f** [comment]
Update on this- I've successfully created a few test maps in Maps4News. Have had a success rate ~90% with this. 

ArcGIS obviously has a lot more going on, but will likely need to be customized for Ops' use. I haven't been able to create anything meaningful. The demo can only be scheduled next week, so we'll learn more then.

**Comment by vishaliyer-18f** [comment]
Also, ArcGIS online is **not** optimized for print. The GSA contact thought that could be problematic, but screenshots are always a possibility

**Comment by MeghanLuecke** [comment]
Thanks @vishaliyer-18f ! This is all very helpful. For ArcGIS Online, here are emails for test accounts: 
VoigtlanderR@state.gov
MeinzenLE@state.gov
AdamsonHL@state.gov
SwansonCL@state.gov
LueckeMH@state.gov
BeeboutTW@state.gov

@beebouttw  please let Vishal know if you want to add any specific folks from upcoming surge teams to have access to the ArcGIS Online test account so they can play with that and Maps4News for comparison. 

Meanwhile, I'll work on Tableau access.

**Comment by vishaliyer-18f** [comment]
@MeghanLuecke Draft here! https://docs.google.com/document/d/1hHqMpcWjw7MEKy0UCGT9zVLG09yWs5qPEm_aeXYGDp0

I will demo this today.
