### ISSUE TITLE
Visual communications primer

### ISSUE THREAD

**Issue by vishaliyer-18f** [18F/dos-ops-center#208]
We believe that the Ops team can benefit from means of visual (non-text) communication like methods like infographics, charts, short videos etc.

We can help them by identifying best practices and tools that enable them to easily create and visual mark-ups.

We'll know we're right if they can incorporate these visual methods and if they can do so without meaningful effort/ time. 

To (in)validate this hypothesis we can:

1. Identify real-world scenarios where location based visuals would enhance communication. (Examples might include evacuation plans, or directions to shelter, or airports)
2. Evaluate different visual communication tools that would help Ops more effectively communicate
3. Ensure that our recommendations work for the Ops team considering available time, resources and skills. 

Note: Mapping is explicitly out of scope for this story since the need for that is well documented, and covered previously in #188

AC

- [x] Research various visual communication media that might be useful to Ops based on previously identifies use cases
- [x] Create visual communications document to share with Ops
- [x] Reconcile this market research report and its recommendations with the mapping research, by scheduling a discussion with Ops to compare the two needs and make a recommendation on whether one single tool could accomplish both or whether we should pursue multiple tools.

**Comment by MeghanLuecke** [comment]
Let's reconcile this with #194.

**Comment by vishaliyer-18f** [comment]
@MeghanLuecke @beebouttw, here's a draft for this- https://docs.google.com/document/d/17pbElFhCrOi4h-p2HkAOexvqNLkksgV6ZSNRkF3t5pI/edit#heading=h.jj2ac9f29jld

The purpose of this doc is to explore whether non map based visual communications could be useful, and we've done that by showing a bunch of examples. It is perfectly reasonable to say, "this is interesting, but we don't really have a need for this". Doc should be pretty self explanatory, but happy to chat.

**Comment by MeghanLuecke** [comment]
@vishaliyer-18f  have we completed the final AC for this yet? I'm not sure I have a clear answer just yet.

**Comment by vishaliyer-18f** [comment]
These would be two different tools, its hard enough to find one that does mapping well :)

**Comment by MeghanLuecke** [comment]
Thanks Vishal - I figured as much, but wanted to be sure we'd confirmed and captured the outcome! I'll close this issue.
