### ISSUE TITLE
Summary of KMS Demo Progress for Bob

### ISSUE THREAD

**Issue by beebouttw** [18F/dos-ops-center#209]
As an Ops Center PM, I would like to provide a high-level summary of our multiple KMS demos this sprint for Ops leadership

AC

- [x] Complete demo reviews of proposed KMS systems under review during this sprint
- [x] Compile notes from those reviews into a single 5-minute brief.

**Comment by brandocalrissian** [comment]
Would include any learnings from demos thus far. These include #182, #203, #204, #205.

**Comment by MeghanLuecke** [comment]
@karareinsel , we've completed the demos anticipated for this specific sprint - however, there are other KMS options we have not yet demo'd or discussed in detail. We may need to repeat this exact same issue for the next sprint.

**Comment by karareinsel** [comment]
@beebouttw @MeghanLuecke - can this issue be closed out given your briefing of Bob on Friday about Huddle and Oxcyon? If other briefings are needed, I recommend creating a new issue to capture the need and we can close out this issue. Thoughts?

**Comment by MeghanLuecke** [comment]
Yes! Closed.
