### ISSUE TITLE
Review vendor and third party sources for Watch info, set up remote interviews

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#21]
As an 18F researcher, I would like to review content and news vendor options currently used or potentially to be used in the future, so that I can have an understanding of the third party tools currently available and future potential. 

AC:
- [x] Get the list of current and pitched groups from Tyler
- [x] Do some research and compile any other options we might have found
- [x] Develop a plan for when to schedule interviews and start scheduling them (Last week of November? Thanksgiving week? First week of December?)

**Comment by beebouttw** [comment]
As promised, here is a quick rundown of who we are working with currently, as well as who we have spoken with previously.  I would love for 18F to speak to several of these folks with me.
[https://app.zenhub.com/files/154224183/1c7462e5-f180-4b9d-870e-6511f8a1cc72/download](https://app.zenhub.com/files/154224183/1c7462e5-f180-4b9d-870e-6511f8a1cc72/download)

**Comment by karareinsel** [comment]
@beebouttw can we move forward with scheduling the calls/demos with Dataminr and InfoViewer for the first week of December?

**Comment by beebouttw** [comment]
@karareinsel Absolutely, I'll reach out to my contacts at both.  I imagine this will take place over Webex or similar -- is there a time that works best for the team?

**Comment by karareinsel** [comment]
Afternoons are generally better to accommodate west coast team member schedules.

**Comment by yowill** [comment]
Considering this closed for now since we have an action plan for next sprint!
