### ISSUE TITLE
Gather details about content types

### ISSUE THREAD

**Issue by durland18F** [18F/dos-ops-center#210]
We believe that an understanding of the complete universe of content types will help us complete the content model and will in turn inform the selection and build of a KMS.

We can help Ops define the universe of content types by having a conversation that captures the purpose and form of each content type, defines who creates them, and notes what metadata applies to each.

We'll know we have a good list when Ops tells us it is complete.

AC
- [x] Schedule time with a representative from CMS and the Watch to review content types
- [x] Take down relevant information about each content type

Support: 
@SwansonCL

**Comment by MeghanLuecke** [comment]
@durland18F I'm tagging in @SwansonCL here as she's back in action and can help figure out how to move this one forward.

**Comment by SwansonCL** [comment]
@durland18F let's schedule this!  I also wonder if Steven Reilly would like to sit in to help him start getting familiarized with the content side.

**Comment by durland18F** [comment]
Yes! I will bug you all via Slack for scheduling.

**Comment by beebouttw** [comment]
Closing this following the completion of CMS and Ops content sessions.
