### ISSUE TITLE
Evaluation of KMS platforms still under consideration of technical needs

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#211]
Here are the mission critical technical needs:

- [ ] Needs to interface with the low/high side flip bridge or equivalent
- [ ] Needs low to high content replication that works through the low/high side bridge flip mechanism.
- [ ] Need to create content on the high side that embeds potentially nested content replicated from the low side.
- [ ] Needs to work with continuous deployment.
- [ ] Needs to parse email headers and associated metadata.
- [ ] Needs to parse email chains and associated metadata.
- [ ] Needs to interface with cables as a data source (low and high).
- [ ] Needs to interface with Infoviewer as a data source.
- [ ] Needs to interface with Dataminr as a data source.
- [ ] Needs to be able to automatically pull metadata from cables and apply relevant KMS tags.
- [ ] Needs to support embedding URLs from public sources (video, photos, live video feeds, imagery...) within content.
- [ ] Needs to support embedding content from any managed data source into content products (cables, other content products, …)
- [ ] Needs to match or exceed NARA records export capabilities of current systems.
- [ ] Needs to allow tracking of content as record types and edit dates to comply with retention schedules.
- [ ] Needs to interface with email for delivery of content products to content consumers.
- [ ] Needs to interface with SMS for delivery of content as push messages to content consumers.
- [ ] Needs to control distribution of content to particular content consumers or groups of users where users may subscribe to multiple channels (email, SMS, portal, phone, …)
- [ ] Needs to allow content consumers to manage what content they receive and through what channel (email, SMS, portal, phone, …)
- [ ] Needs to be performant enough to meet Ops needs for timeliness (measured in seconds, not minutes).
- [ ] Needs to support content creation by non-Ops users.
- [ ] Needs to export data via an API for records retention.

Support
@brandocalrissian 
@karareinsel 
@stvnrlly

**Comment by brandocalrissian** [comment]
We have turned these user needs into things to look at in the KMS evaluation here: https://docs.google.com/document/d/1SukpvTbatt9Dg8GpV_60yOJdwHENIBppM_95liWo_eU/edit#

**Comment by brandocalrissian** [comment]
We'd like to talk with Tom to make sure we understand how the KMS can interface with and support the low/high side flip bridge. We want to ensure we're looking at the specific capabilities of the KMSs to automate content flow from the low to the high side with appropriate traceability.

@beebouttw Would you be able to set up a call with Tom to talk about the low/high bridge? We would expect it to be 15-30 minutes. Someone from Ops would likely want to be on this call to have visibility into this fundamental feature/constraint of any solution.

Some context from the doc in [the previous comment](https://github.com/18F/dos-ops-center/issues/211#issuecomment-479056487):

- Talk with Tom to make sure we understand the low/high side flip bridge
- Understand replication capabilities— can have low side cloud replicate to high side cloud/on-prem through bridge, replicate content blocks and support documents with high side content, too
  - Needs to interface with the low/high side flip bridge or equivalent
  - Needs low to high content replication that works through the low/high side bridge flip mechanism.
  - Need to create content on the high side that embeds potentially nested content replicated from the low side.

**Comment by brandocalrissian** [comment]
We will populate a [sheet in the KMS Eval Worksheet](https://docs.google.com/spreadsheets/d/1oAJY_dylsTBHTT6ODvKBI8GN_5kkrzIm-nVvPORof_8/edit#gid=440282680) with the notes we're taking for this ticket's KMS evaluation.

**Comment by brandocalrissian** [comment]
Split out the criteria carried over from Kosovo into #223.
