### ISSUE TITLE
Create outline for KMS Recommendation document

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#213]
This is the first draft of the document which will be discussed in the April 30 meeting. The draft is intended to be shared with Ops for feedback.

AC:
- [x] Headers and explanatory text describing the flow of the document, providing a high-level view of what the end product will be

Support:
@karareinsel 
@tadhg-ohiggins 
@stvnrlly 
@durland18F 
@matt-dobson

**Comment by karareinsel** [comment]
@brandocalrissian @durland18F @tadhg-ohiggins @stvnrlly @yowill I started the draft of the outline for the KMS recommendations. If you have time today to take a look and add any comments or feedback, it will be much appreciated. Hoping to share this with Meghan and Tyler by tomorrow morning so we can quickly get their feedback and start moving on the writing.
https://docs.google.com/document/d/1TFWKtyWDKZx-njJSLBxaOV0yNltUnFVuWYWndoOUxjA/edit#heading=h.rmyim0q1dqu0

**Comment by karareinsel** [comment]
Link to outline for @MeghanLuecke and @beebouttw to review https://docs.google.com/document/d/1T2J0hlFe3HZ1IGLLD2mydEjtxQWb6cWIQdlCp3j7m0U/edit#

**Comment by brandocalrissian** [comment]
Delivered. Getting feedback and making revisions will be tracked with #214
