### ISSUE TITLE
Create draft of KMS recommendation document for sharing with Ops leadership

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#215]
Goal: get feedback from Ops leadership for revisions before April 30 meeting.

AC:
- [x] Draft ready to share with Ops leadership

Support:
@karareinsel 
@tadhg-ohiggins 
@stvnrlly 
@durland18F 
@matt-dobson 
@MeghanLuecke 
@beebouttw

**Comment by yowill** [comment]
BOOMSHAKALAKA DONE!
