### ISSUE TITLE
Create final draft of KMS Recommendation doc

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#216]
Incorporate Ops' leadership feedback and get revisions accepted before April 30 meeting.

AC:
- [x] Final version of doc accepted by Ops' leadership

Support:
@karareinsel
@tadhg-ohiggins
@stvnrlly
@durland18F
@matt-dobson
@MeghanLuecke
@beebouttw

**Comment by yowill** [comment]
Front load conclusions, graphics as much as possible, long narrative as addendum later in the doc

**Comment by yowill** [comment]
🚢 ed
