### ISSUE TITLE
Test Tableau and PowerBI for dashboard functionality

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#218]
As 18F and Ops team members, I want to use existing DOS dashboard tools (Tableau and PowerBI) to test out ingesting data that Ops currently receives via email, Dataminr, InfoViewer, Consular Alerts websites, SMART cables, Google maps, and upcoming S calls to confirm if these tools could meet Ops needs for a dashboard.

AC:
- [x] Set up dashboards in Tableau and PowerBI to ingest data above
- [ ] Brief the team on results and incorporate the results into constellation of tools recommendations

Support:
@MeghanLuecke

**Comment by MeghanLuecke** [comment]
As a very rudimentary sample for those not familiar with PowerBI, it's got a pretty reasonable interface for creating a dashboard by customizing tiles that can pull from a range of sources. The challenge will be figuring out how to pull from our trickier non-web sources. 
![powerbi dashboard rudimentary sketch.JPG](https://images.zenhubusercontent.com/5bd9b7b31fe0b97de0df8d90/42af8742-0655-47a5-8a9c-728123730d51)

**Comment by beebouttw** [comment]
Here's a screenshot of an active "dashboard" used to track the geographic distribution of News Tickers:

![image.png](https://images.zenhubusercontent.com/5bd840393f15d355c7551ffc/7f66cf59-6ee3-46c8-a4cf-10c59d67f1cd)

**Comment by MeghanLuecke** [comment]
For team's awareness, so far PowerBI looks like it could be a great option for building an internal dashboard for Ops users, but it's not yet clear whether and how we could create such a dashboard for our customers to access. The customer "dashboard" likely needs to be a well-organized, super-searchable website that allows customers to pull all of our content much more easily; it's not yet clear whether a PowerBI-style dashboard would work for that purpose. Still investigating.
