### ISSUE TITLE
Create an interview guide for third party content sources 

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#22]
As an 18F researcher, I want to have a research plan and questions for discussing with third party content sources and vendors that DOS currently or potentially could use, so that I can get review of the capabilities and features available.

Acceptance Criteria:
- [ ] A list of questions for the interview in a progression
- [ ] Share these with Meghan & Tyler for review and feedback ahead of time
- [ ] Integrate any feedback from M&T for the final plan

**Comment by karareinsel** [comment]
@yowill do you think we still need this issue or can it be closed?
