### ISSUE TITLE
Test Etherpad-lite/Drupal solution

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#220]
Concurrent editing is a high-value user need. Would be good to know in higher detail how this combination works.

AC: 
- [ ] Time box for 2 hours and see how far we get

Support:
@stvnrlly

**Comment by MeghanLuecke** [comment]
@tadhg-ohiggins @stvnrlly I know we elevated OneNote API to a higher priority, but any further insights on this question so we better understand whether Drupal's Etherpad option would work for us?

**Comment by tadhg-ohiggins** [comment]
Closed because this is covered by #237 and #239.
