### ISSUE TITLE
Investigate OneNote API

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#221]
As an 18F researcher, I want to better understand how the OneNote API works so that I can figure out how to export and use that data in future integrations, KMS, and other tools solutions.

There's a [OneNote plugin](https://www.microsoft.com/en-us/microsoft-365/blog/2015/05/22/onenote-welcomes-three-new-partners-cloudhq-equil-and-wordpress/
) (built by Microsoft) that publishes content to WordPress. It hasn't been updated since 2015. 
Since concurrent editing is such a high-value user need, it would be good to know more about how this combination works.

AC: 
- [ ] Time box for 2 hours and see how far we get

Support:
@stvnrlly

**Comment by karareinsel** [comment]
@stvnrlly @tadhg-ohiggins Per @MeghanLuecke note, Ops priority it to look at the OneNote API first (vs. Etherpad). Noting it here so that a quick update can be shared with the Ops team (since this issue is timeboxed at 2 hours).

**Comment by tadhg-ohiggins** [comment]
I'm currently working on this; from what the docs suggest, it seems that API access that includes OneNote seems to have been added in 2015, suggesting that the Sharepoint Server version would need to be at least that recent in order to use the API.

**Comment by tadhg-ohiggins** [comment]
Also, it's worth noting again that the OneNote docs explicitly state that the output or export HTML is not the same as the input/native HTML for notes, so notes will definitely not retain all their formatting after being exported.

**Comment by MeghanLuecke** [comment]
Thanks @tadhg-ohiggins and @stvnrlly . What's the status of this OneNote API research? Did you learn more about its integration with Wordpress, or about possibilities of integration with other KMS's?

**Comment by yowill** [comment]
Creating a new issue for the One Note test integration
