### ISSUE TITLE
Document the definition of a dashboard

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#222]
As 18F and Ops team members, we want to define what a dashboard is and is not so that all members of the team are working from a shared definition and can communicate it to stakeholders.

AC
- [x] Draft definition of what Ops wants a dashboard to be and share with 18F and Ops team members for review and approval
- [x]  Add to project glossary
- [x]  Use to inform #218 

Support:
@yowill

**Comment by durland18F** [comment]
Added to glossary with definitions from conversation with Catherine.
