### ISSUE TITLE
Assign weights for criteria evaluated in Kosovo

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#224]
As we did with #206, schedule a time (15-30 minutes) to work together to develop the relative weights/value of the product features evaluated in #201/#211/#223 for Ops to help judge product fit.

Support:
@MeghanLuecke 
@beebouttw 

AC

[ ] schedule session
[ ] complete session and document/assign any necessary follow-up

**Comment by MeghanLuecke** [comment]
@brandocalrissian @beebouttw @RyanV-State @karareinsel @tadhg-ohiggins @stvnrlly when is a good time for us to schedule this discussion? Would folks be available tomorrow after 2:30pm ET?

**Comment by brandocalrissian** [comment]
completed today
