### ISSUE TITLE
Confirm Map Options Pricing

### ISSUE THREAD

**Issue by MeghanLuecke** [18F/dos-ops-center#227]
As an Ops team member, I want to understand the price comparison between using Maps4News (new to State) versus using ArcGIS Online, for which we may be able to use one or two existing licenses (but the details are unclear). We need this information so we can make an informed recommendation to leadership as part of the total constellation of tools.

[ ] Talk to Pete in CSO about existing ArcGIS, and specifically ArcGIS Online, access. 
[ ] Compare with Maps4News quote. 
[ ] Use this to inform other stories focused on the constellation of tools and final report (such as #217); coordinate with Kara.

**Comment by karareinsel** [comment]
Already been addressed.
