### ISSUE TITLE
Prepare to Brief ExecSec Kenna with Bob

### ISSUE THREAD

**Issue by beebouttw** [18F/dos-ops-center#228]
As 18F and Ops team members, we want to prepare a concise, 15-30 minute briefing on Ops' proposed path forward and funding request to be presented to Executive Secretary Lisa Kenna. This is likely to take place the week of My 13, but could pop up sooner; a draft is needed Tuesday May 7. 

AC:

- [x] Concise five slide presentation showing challenge, solution, and anticipated roadblocks (Ops)
- [x] Clear recommendation of Ops' preferred open source solution (Ops)
- [x] Visual evidence to support recommendation (Ops)
- [x] Estimated timeline for acquisition (@MCHopson )
- [ ] Estimated budget for acquisition (@MCHopson )
- [x] Anticipated questions (in house development, viability of other solutions in use by S bureau, etc.) (Ops)

Support:
@MCHopson 
@karareinsel 
@yowill

**Comment by MeghanLuecke** [comment]
Draft 1 of concise presentation complete.

**Comment by karareinsel** [comment]
Draft slide deck has been created by @MeghanLuecke, shared internally at DOS

**Comment by karareinsel** [comment]
@MeghanLuecke shared the slide deck with us. Planning on doing a test-run with Ops on Monday, 5/13 (confirming the time with Meghan).

**Comment by karareinsel** [comment]
The attendees for the ExecSec briefing will be exclusively DOS. 18F has reviewed the slide deck and added notes/comments.
