### ISSUE TITLE
Create procurement documents

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#229]
As an 18F acquisitions officer, I need to prepare the documents to procure a KMS on behalf of the Ops Center so that a solicitation can be put out on the street.

AC
- [x] Fill in the following sections: 1.0, 1.1, 1.2, 1.3, 2.0, 2.1, 2.2, 2.3

Link to agile contract template: https://docs.google.com/document/d/1cB3nwXFycz6kML-taA636_8-zhMVEMR-pOVD4_CpxFc/edit

Support
@karareinsel 
@vishaliyer-18f 
@brandocalrissian 
@MeghanLuecke (pairing)

**Comment by brandocalrissian** [comment]
We had an 18F-team meeting to discuss the desired outcomes of the document and to plan creation of the initial draft. Edits are in process.
