### ISSUE TITLE
Create Operational Dashboard Prototypes

### ISSUE THREAD

**Issue by MeghanLuecke** [18F/dos-ops-center#230]
As Ops and 18F team members, we want to provide visual (ideally interactive) prototypes responding to Ops' leadership request for an operational dashboard so that we can better define user needs and ultimately add a dashboard plan into our roadmap (complete with a recommendation on whether to custom build, add an existing tool to our constellation, or another way forward). 

- [ ] Update paper prototypes
- [ ] Compare PowerBI option against alternatives
- [ ] Develop clickable prototype in PowerBI OR another tool, as determined by AC #2
- [ ] Draft a report or brief presentation summarizing what we learned from prototyping and how this fits into the broader roadmap and constellation of tools

**Comment by karareinsel** [comment]
Closing - work will be addressed by #232 .
