### ISSUE TITLE
PowerBI prototype

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#240]
As 18F and Ops team members, we want to see how far we can get in building a desktop dashboard using PowerBI for Ops internal users so that we can assess technical feasibility for desktop and wall implementation.

AC

- [x] Identify what tiles can be built by Ops and what requires customization
- [x] Identify what data sources can be easily visualized
- [x] Have a rough PowerBI prototype for desktop and/or wall
- [x] Learn if an existing tool (PowerBI) is a good solution is a good fit for dashboard needs

Support
@stvnrlly 
@MeghanLuecke 
@matt-dobson 
@brandocalrissian

**Comment by karareinsel** [comment]
@stvnrlly - @beebouttw and @MeghanLuecke are available to co-work earlier this week on PowerBI if that works for you. Or the co-working can be done on Thursday.

**Comment by beebouttw** [comment]
Now planning to co-work Wednesday, 5/15 @ noon

**Comment by beebouttw** [comment]
@MeghanLuecke and I showed our prototypes and data sets to @stvnrlly today, and walked through the kind of resources we would like to see visualized.  Steven is going to look into a few different tools that might help meet our needs.
