### ISSUE TITLE
Summarize what we've learned from co-editing session

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#242]
As an 18F researcher, I need to analyze what we've learned and summarize our results from the etherpad testing so that we can compare the results in the future. 

AC:
- [x] Present immediate take-away's and results at the sprint Moldova demo on 5/17
- [x] Create a report for the results of the testing

Support
VOLUNTEER HERE

**Comment by karareinsel** [comment]
Link to the experiment report.
https://docs.google.com/document/d/1KcuOjH7P4gKbNzmbkqR83YNSWIzPqB2cahSPPcbtJNg/edit#heading=h.bo8yx38wjfxd
