### ISSUE TITLE
Write research protocol for co-editing testing

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#243]
As a researcher, I want to create a research protocol to test among the Dos team in as close to a real-time scenario to administer a real world test with their team so that we can get the best results possible.

AC:
- [x] Document the process, questions, and hypothesis to test

Support
@matt-dobson 
@vishaliyer-18f

**Comment by karareinsel** [comment]
@durland18F shared test protocols for CMS and The Watch with @MeghanLuecke for her review (5/8). 

CMS - https://docs.google.com/document/d/1C8lrqaAlk1ZvMZeCKROXtmhQCdgT_sD7Yj8PrNRCYUo/edit?usp=sharing

The Watch - https://docs.google.com/document/d/1xMnQN6rGj4pq-CLqUm9aE1WfxLVM3bgi3--0t_dsp0w/edit?usp=sharing
