### ISSUE TITLE
Schedule user research session(s) and secure travel for 18F team

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#244]
As a researcher, I want to have travel and sessions booked so I can execute them and live my normal life!

AC:
- [x] Coordinate with Meghan and Tyler when is the ideal time to get the quorum for the research session
- [x] Get approval for travel 
- [x] Plan travel 

Support
@beebouttw 
@hannahkane

**Comment by karareinsel** [comment]
Travel for @matt-dobson and @durland18F - done. Closing issue.
