### ISSUE TITLE
Gather materials for test scenarios

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#245]
As a researcher, I need to have the resources collected to execute the testing sessions so that we can be as accurate in our scenario as possible. 

- [x] Collect resources needed to mimic the inputs that go into collaborative editing
- [x] Verify what we can bring into space for testing

**Comment by karareinsel** [comment]
@durland18F can you add your estimate when you have a moment?

**Comment by matt-dobson** [comment]
SOS Samples: https://docs.google.com/document/d/1LrSrXiVDPm0ySC3nUNKzk9SwfeQaZHPRbBCyxB8RfXM/edit?usp=sharing
