### ISSUE TITLE
User testing scenario refinement

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#246]
As a researcher, I want to evaluate and refine our process to make sure we're being effective and accurate in the testing scenario.

AC:
- [x] Internal evaluation and review of the workflows
- [x] Evaluating and review scenarios and workflows with Meghan and Tyler to verify we're testing the right thing and represent reality

Support
@matt-dobson 
@karareinsel

**Comment by karareinsel** [comment]
@durland18F I think this is done/almost done but let me know if I'm mistaken. Moving it to in progress.
