### ISSUE TITLE
Prioritization and review CDI and OCCAM wireframes 

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#249]
As a researcher, I want to review and refine information to unpack and better understand CDI wireframes and E&I kick-off sketches so that we can identify any gaps, user context and purpose, and use the learnings to inform possible user scenarios for dashboard user testing.

AC:
- [x] Review existing wireframes
- [x] Present potential scenarios in the dashboard definitions document to Ops to collect feedback 
- [x] The scenarios will be successful if Ops is able to prioritize scenarios for user testing and have agreement on shared definitions of dashboards.

**Comment by yowill** [comment]
Scenario crafting is still ongoing, but it's close to being done

**Comment by karareinsel** [comment]
Link to Mural for prioritization exercise https://app.mural.co/t/gsa6/m/gsa6/1558542964759/2403ee4c87cd991882ea630a2084124b8516459c

@matt-dobson

**Comment by karareinsel** [comment]
@matt-dobson is this issue considered done in light of yesterday's prioritization session?

**Comment by matt-dobson** [comment]
@karareinsel I think so. Thanks!
