### ISSUE TITLE
Write file structure/naming research protocol

### ISSUE THREAD

**Issue by durland18F** [18F/dos-ops-center#258]
As a researcher, I want to create a research protocol to test a file structure and naming convention for the shared drive among the Ops team. This will require a reasonable approximation of the current contents of the shared drive along with its existing structure.

AC:
- [x] Ops supplies existing file structure of shared drive
- [x] Ops supplies descriptions of content within files, and examples as possible and needed
- [x] 18F documents the process, questions, and hypothesis to test

Support:
@MeghanLuecke 
@beebouttw

**Comment by yowill** [comment]
Due for next Thursday in person workshop

**Comment by durland18F** [comment]
Added needs from Ops to AC.

**Comment by yowill** [comment]
**Next steps/needs still outstanding and blocking this issue:**
- [ ] @beebouttw to export the CMS file tree
- [ ] Talk with Meghan and Tyler about proposed taxonomy 
- [ ] Task list from @beebouttw 
- [ ] Documents responsive to tasks from both @MeghanLuecke & @beebouttw 

 With this ^ analysis can start and testing
