### ISSUE TITLE
Create list of follow-up interviews and/or walk-throughs/processes

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#31]
As an 18F researcher, I would like to identify people for follow-up interviews so that I can learn more about particular topics and/or refine learnings from the first round of interviews.

- [x] Create list

- [x] Share list with M&T

**Comment by karareinsel** [comment]
Working draft of list of follow-up interviews

- Meghan Luecke
- Tyler Beebout
- Over the shoulder observation of Amy LeMar Reiman's email in-box

**Comment by RyanSibley** [comment]
Add to the list:

- view crisis.state.gov

**Comment by jeanninehunter** [comment]
Add to the list:
- historian and/or librarian at State

**Comment by RyanSibley** [comment]
Adding more:

-Kevin Gatlin
-Tom Aherns 
-Janice DeGarmo 
-Reggie

**Comment by RyanSibley** [comment]
Adding:

- see list of categories that the subscription services use

**Comment by RyanSibley** [comment]
- Have a look at Everest

**Comment by karareinsel** [comment]
Interviews being scheduled for the week of 11/26: Meghan Luecke, Donald Hicks, walk-through of crisis.state.gov, walk-through of Amy's inbox, historian, librarian.

**Comment by yowill** [comment]
Tracking phase 2 here: https://github.com/18F/dos-ops-center/issues/37
