### ISSUE TITLE
Team synthesis of interview notes

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#32]
As an 18F researcher, I want to review and synthesize the notes from the interviews that were conducted Nov. 5 - 9 so that I can identify key take-aways, big picture questions, and focus areas that will help us identify further areas of research, SME interviews, and initial thoughts about personas and user journey maps.

Approach:

1.   Each 18F team member reviews their notes for a given interview.
2.  After reviewing their personal notes for a given interviewee, the 18F team member adds their key take-aways for that interview to the Key Take-aways section at the top of each interview notes document.
3.  Rinse and repeat for each of the 31 interviews.

- [x] Kara 
- [x] Will
- [x] Ryan
- [x] Jeannine
- [x] Tadhg
- [x] Mark
- [x] Brandon

**Comment by yowill** [comment]
https://docs.google.com/spreadsheets/d/101ECtvv2jXBHwBBMLTYyJE5lKLC3QgSRoKM9_mBmEY8/edit#gid=1805682807
