### ISSUE TITLE
Team synthesis - parking lot for big ideas

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#34]
As an 18F researcher, I want to capture big ideas, questions for discussion in a "parking lot" document for further exploration.

Process:

- As each team member synthesizes interviews, they add inputs to the parking lot document. These are not take-aways for the individual interviews - instead they are big picture things that we want to capture and come back to. The parking lot is for ideas/questions that aren't specific to only one interview.

- [x] Add to the parking lot document

**Comment by yowill** [comment]
https://docs.google.com/spreadsheets/d/101ECtvv2jXBHwBBMLTYyJE5lKLC3QgSRoKM9_mBmEY8/edit#gid=1805682807

**Comment by RyanSibley** [comment]
Here's the doc for your big ideas, topics for discussions, follow up research ideas, etc...

**Comment by yowill** [comment]
Completed!
