### ISSUE TITLE
Schedule Phase 2 of follow up interviews

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#37]
As an 18F Researcher, I want to conduct interviews with the second phase folks to further investigate DOS organization and knowledge management structures. 

Background, second wave of this:
https://github.com/18F/dos-ops-center/issues/31

Acceptance Criteria:
- [x] Deliver the list of names to M&T
- [x] Set up interviews with:
- [ ] ~~Janice DeGarmo - Deputy Director of M/PRI~~ She will be replaced with Obel (Kobi) Gillette
- [x] Kevin Gatlin - IRM, building the analytics platform
- [x] Tim Aherns - IRM, building the analytics platform
- [ ] Director of the Cloud Program Office
- [ ] Ken LeVolpe - part of the Cloud Program Office, used to be a deputy director in ExecTech
- [ ] Cornella Donohue - Director of Outreach and training, manages inputs to intranet and internet

**Comment by karareinsel** [comment]
I recommend that we schedule the remaining interviews for after the Bob briefing. This applies to any interviews that are not yet scheduled - Janice DeGarmo, Kenny LaVol, the Cloud Program office, and Cornella Donohue.

**Comment by karareinsel** [comment]
Obel (Kobi) Gillette will replace Janice DeGarmo.

**Comment by karareinsel** [comment]
Confirmed with Kenny LaVolpe that we'll follow up with him the week of December 17 to confirm his phone interview. He'll be OOO 12/14, 12/24, 12/26 and 1/2.

**Comment by karareinsel** [comment]
Moved the remaining interviews that still need to be scheduled to #55
