### ISSUE TITLE
Developing working list of focus areas for KMS Track

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#38]
User Story:
As an 18F researcher, I want to create and prioritize focus areas, so that I can organize the areas that need further refinement, identifying holes, gaps in knowledge.

Background Info:

Acceptance Criteria:

- [x] Documentation

 of the list of focus areas

**Comment by RyanSibley** [comment]
Mural is here: https://app.mural.co/t/gsa6/m/gsa6/1542736437344/986a544f9dd5bce0583aa7a24eefd1fc976db79a

**Comment by karareinsel** [comment]
Working document of focus areas
https://docs.google.com/document/d/1C4KLYKdVh2BqLOp116ssX1U6ayIGyq-09wimk08yePM/edit#
