### ISSUE TITLE
Developing working list of focus areas for Content Strategy Track

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#39]
User Story:
As an 18F researcher, I want to create and prioritize focus areas, so that I can organize the areas that need further refinement, identifying holes, gaps in knowledge.

Background Info:

Acceptance Criteria:
Documentation of the list of focus areas

**Comment by RyanSibley** [comment]
Mural is here: https://app.mural.co/t/gsa6/m/gsa6/1542820054441/8b6381a7bcff1b178c4e2e9ff9da32052bee8bad

**Comment by RyanSibley** [comment]
Starting work on needs/focus areas in "epic" fashion here: https://docs.google.com/document/d/1SyUpK7ZztoqZk9mleVZQI2l9AAfsGfXX2-nhUAuY9GE/edit
