### ISSUE TITLE
Create (living) glossary of terms

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#43]
To keep the entire team (Department of State + 18F) aligned with terminology, create a glossary of terms available and editable by all (suggestion: in the github repo).

The initial version should start with definitions produced during the PA phase.

**Comment by yowill** [comment]
Get it started, weave in the terms we review, link to from the Read.me on Github

**Comment by yowill** [comment]
Here's a placeholder in the wiki to start rockin out on these: https://github.com/18F/dos-ops-center/wiki/Living-Glossary

**Comment by jeanninehunter** [comment]
Here's the document where we can park terms, wordsmith them before adding to the wiki: https://docs.google.com/document/d/1mE9VGUU51ItpAexFobJl49rp8gAaBV48zGGSh07OTzY/edit#

**Comment by yowill** [comment]
Lots of updates: 
https://github.com/18F/dos-ops-center/wiki/Living-Glossary

**Comment by yowill** [comment]
This is pretty awesome and ready for at least the 2 points of work we estimated here!
