### ISSUE TITLE
Developing the Content strategy 101 training

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#44]
As a DOS employee, I would like to understand the fundamentals of content strategy so that I can begin to develop the skills and knowledge necessary to develop and own content strategy at the conclusion of the engagement with 18F, and what the role and skills that are needed for a Content Manager in DOS.

AC

- [x] 18F develop training materials
- [x] Schedule training with assistance from DOS for following Sprint Djibouti

**Comment by RyanSibley** [comment]
https://docs.google.com/presentation/d/1wjRw43wDD962XNU94MQsQWVslmOkNMnbnBtmMkUR4Xc/edit#slide=id.gf774b1724_1_70
