### ISSUE TITLE
Create interview guides for Analytics platform

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#45]
As an 18F researcher, I want to review and update the interview guides to add new questions and context for the Phase 2 interviews:

Background info: 
(also sometimes referred to as MPRI)
Previous interview guides: https://drive.google.com/drive/u/1/folders/1eR9apAlR6AHiQvDahLAJ0gxI81StCyAP

AC:
- [ ] Review the previous guides
- [ ] Update them for the Phase 2 folks

**Comment by karareinsel** [comment]
Draft interview guide - https://docs.google.com/document/d/1oB-S-aLvJd9cF9tLybH2WNTQ4sHwDWlDU_Ft3wV-pFs/edit#. @tadhg-ohiggins and @yowill and @brandocalrissian can you take a look and add questions?

**Comment by brandocalrissian** [comment]
I believe we completed this task (and performed the interview!)
