### ISSUE TITLE
Actually do the Phase 2 interviews 

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#50]
As an 18F researcher, I want to conduct more interviews so that I can learn more about the unknown areas of DOS.

AC:
Complete the interviews we have scheduled for this week:
- [x] Donald Hicks
- [x] Historian
- [x] Librarian
- [ ] Dataminer
- [x] Infoviewer
- [x]  Kevin Gatlin - IRM, building the analytics platform
- [x]  Tim Aherns - IRM, building the analytics platform

...potentially more (like those below)
  Janice DeGarmo - Deputy Director of M/PRI
  Director of the Cloud Program Office
  Ken LeVol - part of the Cloud Program Office, used to be a deputy director in ExecTech
  Cornella Donohue - Director of Outreach and training, manages inputs to intranet and internet

**Comment by karareinsel** [comment]
The Dataminr interview will be scheduled once introductions have been made between the 18F and Dataminr teams.

**Comment by karareinsel** [comment]
Closing out this issue. The Dataminr interview is blocked until DOS can facilitate introductions to the Dataminr team.
