### ISSUE TITLE
Deliver the Bob briefing

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#53]
Deliver the pre-holiday briefing to Bob, Amy and Belinda which will cover a high level synthesis of the research and a review of the roles & responsibilities for the CM and PM positions.

AC:
- [x] Confirm the date
- [ ] Deliver the briefing.

**Comment by beebouttw** [comment]
The Brief will be held in room 7522, with the window and the whiteboards.  Thanks for reserving, Meghan!

**Comment by yowill** [comment]
DONE!
