### ISSUE TITLE
Prepare for the Ops Center briefing

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#54]
As Bob (or Amy or Belinda), I would like a pre-holiday briefing so that I can understand the key learnings/take-away's from the interviews and the roles & responsibilities for the CM and PM positions so that hiring decisions can be made by the end of December.

Additional Materials: 
Documentation for what current positions look like to show them examples

AC:
- [x] Schedule the briefing @MeghanLuecke @hannahkane 
- [x] Synthesize key learnings from interviews
- [x] Prepare draft job descriptions for the content manager and product manager roles
- [x] Prepare additional materials for the CM/PM discussion (TBD)

**Comment by yowill** [comment]
https://github.com/18F/dos-ops-center/issues/52

**Comment by yowill** [comment]
https://github.com/18F/dos-ops-center/issues/51

**Comment by hannahkane** [comment]
I see the box is checked for scheduling this, but I don't believe it's been confirmed. We've held two time slots—Monday, the 17th at 2:30pm ET and Tuesday, the 18th at 2pm ET. @beebouttw - are you able to confirm which works for folks?

**Comment by beebouttw** [comment]
@hannahkane @MeghanLuecke I've confirmed Belinda, Amy, and Bob for Dec 18 @ 2:00pm.  We can hold the meeting in Bob's office, a task force room with a large display screen, or, if preferred, I've booked a conference room on the 7th floor that can accommodate about 20 people in an unclass space.

**Comment by karareinsel** [comment]
Our preference would be for the 7th floor conference room space that is unclass (and therefore would be laptop friendly). @beebouttw does the conference room have a screen so we can project slides?

**Comment by beebouttw** [comment]
I don't believe State has any rooms that allow you to connect an outside computer to a screen.  You can present directly from a laptop in the unclass conference space, or you can send a presentation ahead of time and we can display it from a networked computer.

You don't have to make the decision now, I have both rooms booked.
