### ISSUE TITLE
Follow-up interviews - records management, digital historian, IRM

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#55]
Recommend scheduling these interviews for after the Bob briefing.

- [ ] Digital Historian Joe Wicentowski
- [ ] Records management office
- [ ] Alen Kirkorian and Jonathan Olsson - both are with IRM and helping the Watch redesign a new alternative to subscription services
- [x] Adam Cowdery - Cloud SME for DS

Adding the following interviews that were blocked from being scheduled and completed in sprint 3.

- [ ] Director of the Cloud Program Office
- [ ]   Ken LeVolpe - part of the Cloud Program Office, used to be a deputy director in ExecTech
- [ ]   Cornella Donohue - Director of Outreach and training, manages inputs to intranet and internet
- [ ]  Obel (Kobi) Gillette (replacing Janice DeGarmo)

**Comment by karareinsel** [comment]
Additional information from Digital Historian Joe Wicentowski about the CMS that is used by the Office of the Historian.

_XML database (free and open source, see https://exist-db.org), to power the website and the content management applications we are building atop it; in the meantime we edit our content with oXygen XML Editor (https://oxygenxml.com).  We store all of our raw data and code in our repositories on GitHub (https://github.com/HistoryAtState).  Documentation for our system can be found at https://github.com/HistoryAtState/hsg-project/wiki.  

We adopted XML and, in particular, the Text Encoding Initiative vocabulary for our content because it can accommodate our semi-structured, historical, and digitized or born-digital documents; its semantic tags also allow us to enrich the content, identifying people, places, organizations, terms, etc. in our texts and linking them to authority files or controlled vocabularies; and it’s an open standard used widely in universities, libraries, and digital text projects.  

The taxonomy that has stitched several of our datasets together is available at https://history.state.gov/tags (or https://github.com/HistoryAtState/tags), but we are in the early stages of reconceiving and vastly expanding the entity types and number of items included to overcome limitations in the original structure, and to take advantage of the reference data provided by the Department’s Master Reference Data initiative (available on OpenNet at http://mrd.state.sbu).  

In contrast to a traditional relational database that would require us to shoehorn or shred these documents into relational tables, a native XML database like eXist allows us to store documents in whatever structure is needed to capture them and query/analyze/publish them flexibly, whether they be a 1,200 page book from the 1860s (or 1980s), an archive of emails, or a 6,000-record database of Department officials.  

Our servers run in the Amazon Cloud, and we can also have a complete copy of our site running on our workstations by installing the hsg-project files linked above._

**Comment by yowill** [comment]
Broken into separate issues  #70 #69
