### ISSUE TITLE
Share existing guidance about agile task management

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#57]
Ideally in the context of the github tools we're using in the project.

Goal: have something describing the process DoS can share internally for learning and socializing.

Not asking for new content to be created.

**Comment by karareinsel** [comment]
@hannahkane has a draft ready for review - https://docs.google.com/document/d/1B4XIyEQpcTyzDvgiwLD4ZrMgzTcyHFLS_iQTARtmML4/edit#
