### ISSUE TITLE
Review documents - approved hardware & scripts, MemCon

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#58]
These are the documents that were blocked in #40 . Waiting on 

- [x] NIST Validated Product List
- [x] Pick list of approved scripts
- [x] Potentially a template of a MemCon or redacted version.

**Comment by beebouttw** [comment]
No complete and current NIST-validated list appears to exist, but NIST has a searchable database that can be accessed here:  https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/validation-search?searchMode=validation&family=Prefix&productType=-1&ipp=250

**Comment by beebouttw** [comment]
[https://app.zenhub.com/files/154224183/8963e36d-4bb0-4e69-a583-10cfff19356d/download](https://app.zenhub.com/files/154224183/8963e36d-4bb0-4e69-a583-10cfff19356d/download)

This is an OLD memcon (1982) but absolutely echoes the current format.  It's more useful to see a declassified real memo than a staged or template current memo.

**Comment by brandocalrissian** [comment]
Need more detail on "pick list of approved scripts"

**Comment by brandocalrissian** [comment]
Think this was in reference to PowerShell scripts

**Comment by beebouttw** [comment]
Pick list added as commit to repo:  https://github.com/18F/dos-ops-center/blob/master/Pick%20List%20Powershell%20Scripts.docx
