### ISSUE TITLE
Create a content model

### ISSUE THREAD

**Issue by RyanSibley** [18F/dos-ops-center#59]
Create a content model that allows you to  know *who* uses *what* bits of content *in what context* in order to better deliver content to make it findable and usable for its intended audience. In other words, begin organizing content. Additionally, this work will involve:
- Creating a filing system for products that exist digitally and in possibly in analog
- Maintaining and creating a metadata system

An example of how to start this work would be to treat content products as objects.

**Exercise: Treating content types as objects and assigning characteristics to help organize them.**

Types of product:

### News
- Events that are breaking and of relevance to the State department

News products could be:
Briefs
Alerts 
Situation reports 

### Summary
- Reports that include all that’s known about an incident 

Summary products could be:
Safety Overseas Summaries
Briefs
Situation reports 

### Reflective or expository
- Lessons learned
- Corrections

Reflective or expository products could be:
Lessons learned
Corrections
Guidance 
Decision points

### Instructional
- Guidance
- Lessons learned

Instructional products could be:
Guidance
Lessons learned
Templates
Forms

**Comment by RyanSibley** [comment]
related to #114

**Comment by yowill** [comment]
Supplanted by work in progress and already finished!
