### ISSUE TITLE
Create materials for the product management portion of the 12/12 working session

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#61]
As an 18F product manager, I want to create PM resources/materials so that I can train the Ops Center staff about PM fundamentals in the working session on 12/12 and they will be able to identify the best candidates for the PM role.

- [x] Draft PM job description
- [x] Identify goals for the PM portion of the working session
- [x] Develop exercises

**Comment by karareinsel** [comment]
Working document for PM simulation exercise - https://docs.google.com/document/d/1ThVxT_R41Ysf3TepH08It_O8dtPYqTF1wlWRn4MoRQo/edit

Draft PM job description - https://docs.google.com/document/d/1Qg_T-8bBCzfFypXmS2jHPWoBGln-aIlKemuaCrzcVY0/edit#

**Comment by yowill** [comment]
Looks like this is all set for the shindig today!
