### ISSUE TITLE
Schedule interview with Information Assurance - Scott Sumpter

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#62]
As an 18F researcher, I would like to speak with a member of the Information Assurance Office so that I can understand when and how new cloud-based platforms are reviewed and approved.

- [x] Identify representative from IA - Scott Sumpter
- [x] Schedule interview with IA representative

**Comment by beebouttw** [comment]
@karareinsel identified and reached out to Miriam Cohen, S Bureau's former (and possibly current) rep with IA.

**Comment by karareinsel** [comment]
Per Miriam Cohen's email on 12/13, Scott Sumpter is the right person to speak with from IA. @beebouttw and @MeghanLuecke are working to schedule a call with Scott on 1/4 or 1/7.

**Comment by karareinsel** [comment]
Have tentatively scheduled the call with Scott for 1/7 (1:00 - 2:00 pm ET).

**Comment by karareinsel** [comment]
Scott's interview had to be canceled due to the shutdown on 1/7. Now that work has resumed, I've reopened this issue so that we can schedule his interview to take place during spring Ghana.

**Comment by karareinsel** [comment]
Scheduled for Monday, 2/11, 4:00 - 5:00 pm ET.
