### ISSUE TITLE
Schedule interview with Michelle Sparrow-Walker

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#63]
As an 18F researcher, I would like to speak with Michelle Sparrow-Walker of the Cloud Program Office so that I can understand the scope of the Cloud PMO and how it might impact KMS recommendations.

- [ ] Schedule interview with Michelle Sparrow-Walker

**Comment by karareinsel** [comment]
@beebouttw contacted Michelle on 12/13, waiting to hear back.

**Comment by karareinsel** [comment]
@beebouttw any word from Michelle?

**Comment by beebouttw** [comment]
She's showing as OOO for this week, and her message says she'll be out through Friday.  I've made a calendar tap to follow up with her next Monday, but this looks blocked for the time being.

**Comment by karareinsel** [comment]
Closing out this issue due to it's prolonged blocked status.

**Comment by brandocalrissian** [comment]
We have made contact with Michelle Sparrow-Walker and been referred to her calendar coordinator.

**Comment by brandocalrissian** [comment]
Moved this to in progress since it's happening over email communication

**Comment by karareinsel** [comment]
@beebouttw do we think we'll be able to schedule a call/meeting with Michelle by the end of this sprint? Not that the actual meeting needs to happen by this Friday, just that we're able to do the scheduling by this Friday?

**Comment by beebouttw** [comment]
@karareinsel Fair question.  I do think I can schedule it this sprint, but the assistant Michelle directed me to was let go over the weekend (!!) so I need to find a new contact.  Should be doable.

**Comment by MeghanLuecke** [comment]
Would be glad to join this interview if possible and appropriate!

**Comment by beebouttw** [comment]
Alright, new contact located.  I reached out to her, CC'ing you and Will.  Meghan, I'll be sure you're looped in as we finding dates.

**Comment by beebouttw** [comment]
Double tracked with Danielle Ginyard

**Comment by beebouttw** [comment]
Received dates for meeting from Danielle Ginyard:

Tues, Mar 5th                  11AM-12PM
Wed, Mar 6th                  3-4PM
Thurs, Mar 7th                 2-3PM
Fri, Mar 8th                      11AM-12PM; 3-4PM

Mon, Mar 11th                930-1030AM
Wed, Mar 13th                3-4PM
Fri, Mar 15th                    10AM-12PM; 1-4PM

**Comment by beebouttw** [comment]
Scheduled for Friday March 8, 3:00-4:00PM ET

**Comment by karareinsel** [comment]
@beebouttw is the interview going to be in person or over the phone? Our preference is phone if possible.

**Comment by beebouttw** [comment]
I agree, by phone is preferable.  I'll set up a conference line and pass that information along to Danielle/Michelle.
