### ISSUE TITLE
Complete the interview with Information Assurance - Scott Sumpter

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#64]
Do the actual interview for #62 

- [x] Complete interview with Information Assurance representative, Scott Sumpter

**Comment by yowill** [comment]
Interview guide started here: https://docs.google.com/document/d/1yWG_NAwWxUXJs4TJ9j8Q25V4bxmQ_NUngfjfH9y18Tg/edit

**Comment by yowill** [comment]
Finished Monday afternoon
