### ISSUE TITLE
Complete the interview with Michelle Sparrow-Walker

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#65]
Complete the interview for #63 

- [x] Complete the interview with Michelle Sparrow-Walker 
- [x] Scheduled for Friday, 3/8, 3:00-4:00PM ET.  
- [x] Call in: 202-647-0817 #51853

Support
@karareinsel 
@brandocalrissian

**Comment by yowill** [comment]
We're waiting on response to book and execute this, but it doesn't seem like this will happen before the end of the sprint.

**Comment by yowill** [comment]
Notes for the interview: https://docs.google.com/document/d/1BVI59esTH-UVJiWOCL3S40XTM-_owrxwaOcbQVyRZ9g/edit#heading=h.zcuiqdccueai

**Comment by karareinsel** [comment]
Closing out this issue due to it's prolonged blocked status.

**Comment by brandocalrissian** [comment]
Looks like we're getting movement from this again with an intro from Alen Kirkorian. Reopening.

**Comment by brandocalrissian** [comment]
The interview is not yet scheduled.

**Comment by brandocalrissian** [comment]
Interview is scheduled for sprint Iran.

**Comment by karareinsel** [comment]
@beebouttw can you share Michelle's contact info (or her assistant's)? I want to add her to the invite with the Google Meet info.

**Comment by beebouttw** [comment]
Michelle Sparrow-Walker:  Sparrow-WalkerM@State.gov -- (202) 634 3877
Danielle Ginyard (her EA):  GinyardDC@State.gov -- (202) 453 9859

**Comment by MeghanLuecke** [comment]
Closing this out (but please holler if there's still follow-up that fits in this issue).
