### ISSUE TITLE
Create the buckets for content products 

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#66]
As a content strategist, I want to organize the first draft of content buckets to show the DOS team, so that we can get a view of the total array of products we need to serve.

Background info:
Use and expand these buckets: https://github.com/18F/dos-ops-center/issues/59

AC:
- [x] Create the first draft of architecture/structure of product buckets 
- [x] Review with DOS for feedback in the working session on Wednesday
- [ ] Add any other buckets we identify

**Comment by RyanSibley** [comment]
First draft is here: https://docs.google.com/document/d/1Qa3vqYwkLUJ866x-ia4KEvMVX5bM0gHu2y1v86LzCd4/edit#

**Comment by RyanSibley** [comment]
Related to #59

**Comment by yowill** [comment]
Done! Notes from the session here: https://docs.google.com/document/d/194OZFVMhOGp67gLutVIkM4DpoOBdikrLxoRvNgPoGME/edit#
