### ISSUE TITLE
Schedule interviews for Sprint France after holidays - digital historian, new sub svcs, Kenny LaVolpe

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#69]
Schedule:
- [ ] Digital Historian Joe Wicentowski
- [x] Alen Kirkorian and Jonathan Olsson - both are with IRM and helping the Watch redesign a new alternative to subscription services
- [x] Ken LeVolpe - part of the Cloud Program Office, used to be a deputy director in ExecTech

**Comment by beebouttw** [comment]
@karareinsel contacted Joe Wicentowski, Kenny LaVolpe on 12/13, asked to schedule after holidays.  Awaiting response.

**Comment by beebouttw** [comment]
Checked box for Alen Kirkorian -- in meeting he intimated he booked a time with 18F, and that Jonathan Olsson had been pulled into a different project.  That interview appears to be scheduled.

**Comment by karareinsel** [comment]
Working to confirm a time with Alen - trying to schedule a call for the first week of January. Unchecked the box for now until a time is nailed down.

**Comment by karareinsel** [comment]
Circled back with Joe and Kenny - working to confirm the time for the first week of January.

**Comment by karareinsel** [comment]
Confirmed

- Alen Kirkoran - Jan. 3, 2:00 - 3:00
- Kenny LaVolpe - Jan. 3, 3:30 - 4:30

**Comment by karareinsel** [comment]
Followed up again with Joe - working to confirm a call on Jan. 4.

**Comment by karareinsel** [comment]
Blocked until we hear back from Joe, digital historian.

**Comment by karareinsel** [comment]
@MeghanLuecke and @beebouttw just letting you know this issue is blocked while we wait to hear back from Joe.

**Comment by karareinsel** [comment]
Created #99 for the interview with Joe so I'm closing out this issue.
