### ISSUE TITLE
Schedule interviews for Sprint France - records mgmt, outreach, MPRI

### ISSUE THREAD

**Issue by yowill** [18F/dos-ops-center#70]
Schedule:
- [x] Records management (Clarence Finney)
- [ ] Cornella Donohue - Director of Outreach and training, manages inputs to intranet and internet
- [x] Obel (Kobi) Gillette (replacing Janice DeGarmo)
- [x] Nick Perry - Sales for potential CMS vendor Everbridge

**Comment by beebouttw** [comment]
Added Everbridge Interview to sprint France planning.

**Comment by beebouttw** [comment]
Reached out to Nick Perry from Everbridge and Clarence Finney from Records Management.  Hoping to set up interviews for week of January 7.  Meghan is reaching back out to Carmella and Kobi with updated windows.

**Comment by jeanninehunter** [comment]
Would be curious to find out if Clarence is a colleague of suggested interviewees from IPS' records management office Tim Katz (division chief for records management at IPS) and Richard Kootz, who is doing work to capture records and context in a systematic way.

**Comment by MeghanLuecke** [comment]
>           Would be curious to find out if Clarence is a colleague of suggested interviewees from IPS' records management office Tim Katz (division chief for records management at IPS) and Richard Kootz, who is doing work to capture records and context in a systematic way.

Jeannine: Clarence is the Records Deputy Director for the Executive Secretariat within the S Bureau. My understanding is it's Tim Kootz who's a division chief at IPS - he is part of the A Bureau. So while he and Clarence might interact, they're in not only different offices but different bureaus. Who was the other person (Katz?)? Was it Richard Kirsch maybe?

**Comment by MeghanLuecke** [comment]
Kobi and Carmella are still OOO so I will continue to try them next week.

**Comment by jeanninehunter** [comment]
@MeghanLuecke Yes, it's Tim Kootz and Richard Kirsch. Thank you for clarifying.

**Comment by karareinsel** [comment]
Clarence Finney (records management) scheduled for 1/8 (2:00 - 3:00 ET).

**Comment by karareinsel** [comment]
Alerting @beebouttw and @MeghanLuecke that I've added the blocked label since we're still waiting to hear back from a few folks about their availability.

**Comment by MeghanLuecke** [comment]
Kobe Gillette is out for paternity leave but working remotely part-time. I consider this interview still blocked, but will update the group if he has availability with his new work schedule.

**Comment by MeghanLuecke** [comment]
Kobe G called Meghan from leave and offered to serve as a resource in March or beyond (when he is back in office) if we hit additional roadblocks identifying IT contacts or understanding the Department's development and approvals processes. Kobe formerly worked in DS for 12 years and is now on detail from the A Bureau, working with M/PRI to establish the new Center for Data Analytics. He has experience working on numerous previous software development projects across State, and is familiar with the Department's current capabilities/structures/licenses/etc for work with Azure, AWS, ServiceNow, and Salesforce.

**Comment by karareinsel** [comment]
Closing out this issue due to it's prolonged blocked status for Kobi Gillette and Cornella Donohue.
