### ISSUE TITLE
Schedule Content Modeling Session with Broader Ops Team

### ISSUE THREAD

**Issue by MeghanLuecke** [18F/dos-ops-center#72]
As an Ops-18F project lead and crisis management strategist, I want to solicit broader participation from Ops colleagues in content modeling work so we can train key stakeholders and hone our first drafts. 

AC
Coordinate with Ryan, Kara, and Will to identify the right timeline/which sprint
Coordinate with Tyler and others in Ops to set a date

**Comment by yowill** [comment]
Tyler spoke with Holly and Ashley today and there's only 1 member of their leadership in on a given day. There's no resistance to having everybody come in for a session. They could find what's ideal for Amy and piggyback off that. @beebouttw is going to investigate and find dates/times.

**Comment by yowill** [comment]
Back and actively being worked on!

**Comment by brandocalrissian** [comment]
Tentatively scheduled on DoS side for Friday, Feb 8, 1pm. Amy/Belinda would need to drop early after 45-60 minutes. Rest of team could likely stay on until 3pm. (per Meghan at stand-up today)
