### ISSUE TITLE
Complete the interview with Alen Kirkorian & Ryan Voigtlaender

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#74]
AC

- [x] Complete the interview with Alen Kirkorian & Ryan Voigtlaender

**Comment by karareinsel** [comment]
Alen is very devoted to helping Ops.

**Comment by karareinsel** [comment]
Blocked due to government shutdown.

**Comment by yowill** [comment]
Interview guide set up to prepare: https://docs.google.com/document/d/1bKwpq0tGIR04kpsKyrr9fqf7XsbJP-3grUPYrKIj650/edit#

**Comment by karareinsel** [comment]
Updating the interview guide to reflect the work that Alen and Ryan are doing with the Ops Center on subscription services improvements.

**Comment by yowill** [comment]
Done! Wow
