### ISSUE TITLE
Feedback plan development - gather, receive, and act on feedback

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#78]
As an 18F researcher, based on the information collection during research interviews, I want to develop a draft/sketch/foundational direction for how to develop a feedback mechanism and process (how to solicit feedback, receive feedback and act on feedback if necessary).

AC

- [ ] Develop draft recommendations for soliciting feedback
- [ ] Develop draft recommendations for receiving feedback
- [ ] Develop draft recommendations on how to act on feedback

**Comment by brandocalrissian** [comment]
We did take what we've learned from our research and sketched out the "land of the possible" related to establishing feedback loops between Ops and its customers.
