### ISSUE TITLE
Investigate what it takes to extract data from Sharepoint

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#85]
As an 18F researcher, I want to understand the level of effort and complexity to extracting data from Sharepoint so that I can assess how this will impact the implementation of the Ops Center KMS.

This is one of the issues in the Unknown column in the KMS repo - once we understand what's involved with extracting data from Sharepoint, we'll be able to refine/define user needs and align it with the appropriate KMS focus area. 
https://github.com/18F/dos-ops-center-kms/issues#workspaces/dos-ops-center-kms-5c264892f9cceb5e65c195ee/boards

**Comment by brandocalrissian** [comment]
Tyler has pulled a lot of data out of Sharepoint for other projects.

**Comment by yowill** [comment]
Split into #150 #151
