### ISSUE TITLE
Investigate what it takes to extract data from email

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#86]
As an 18F researcher, I want to understand the level of effort and complexity to extracting data from email so that I can assess how this will impact the implementation of the Ops Center KMS.

This is one of the issues in the Unknown column in the KMS repo - once we understand what's involved with extracting data from email, we'll be able to refine/define user needs and align it with the appropriate KMS focus area.
https://github.com/18F/dos-ops-center-kms/issues#workspaces/dos-ops-center-kms-5c264892f9cceb5e65c195ee/boards

There's an exception for Office 365 to have email categorized as a SBU. Who controls those? How do they get created? etc.

AC:
- [ ] Find out if it's possible and how

At this point we should only deal with unclassified information.
Split into at least two pieces:

- [ ] Extracting historical email data as a one-off or periodic process.
- [ ] Extracting information from email in real-time as part of an automated or semi-automated process.

**Comment by tadhg-ohiggins** [comment]
It's likely that there will be different answers depending on whether we want to:

- Extract data server-side or client-side.
- Extract data in bulk or in ad-hoc fashion.

**Comment by yowill** [comment]
Break into two issues, one for historical data, one for real time importing

**Comment by karareinsel** [comment]
Closing this issue since the work is now being handled by #146 and #147.
