### ISSUE TITLE
Identify research/feedback methods/processes/techniques for the Ops Center

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#87]
Develop a list of methods, processes, and/or techniques that the Ops Center can use to research and gather feedback from its users. 

https://docs.google.com/document/d/1BJYGVbiEAU5J1hmUvMIBFhRAcxb4JpgZcnnVidE2wfw/edit#heading=h.5oipywmmrz0h

AC:
We've aligned these methods against the research needs we started

**Comment by brandocalrissian** [comment]
We have a draft of recommended feedback techniques that best fit the Ops/DOS environment. We list what they are, what they uncover, examples, the essential steps, and levels of effort for researchers and participants.

We also list methods we do not recommend (what they are, what they uncover, examples) and include why we do not think they fit Ops's needs at this time.

Still need to put our bullet list description of Ops/DOS environment and constraints into prose to tie it all together.
