### ISSUE TITLE
Identify which research goals can be addressed by specific research methods

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#88]
Define and identify the types of information that can be learned from each research method that can be used by the Ops Center to gather feedback. Practical, with a little pixie dust.

AC:
- [x] Alignment as a team identifying the goals with the methods and how they line up with each other
- [x] Artifact mapping them somehow, a playbook or guide, State Department tailored method cards

**Comment by brandocalrissian** [comment]
We have a start to this in the "what you can learn" content of #87 and a few unknowns already identified on the KMS track [user need board](https://github.com/18F/dos-ops-center-kms/issues/24#workspaces/dos-ops-center-kms-5c264892f9cceb5e65c195ee/boards?repos=163426891&showClosed=false&showEstimates=false). Starting to fill out documentation mapping unknowns (learning is the research goal) to research methods.
