### ISSUE TITLE
Fill out understood KMS table stakes functionality pertinent to product/vendor selection

### ISSUE THREAD

**Issue by brandocalrissian** [18F/dos-ops-center#93]
As a member of this effort, I need a common understanding about what to expect from any KMS solution so that important capabilities are not forgotten and can be weighed with other needs.

e.g. it needs to be capable of supporting A&A security oversight, have regular updates and a large enough developer community...

AC:
- [x] Flesh out the list better
- [ ] Run feedback past users (sanity check with Ops team)

Support
@karareinsel 
@tadhg-ohiggins

**Comment by MeghanLuecke** [comment]
Looking forward to helping with the "sanity check" - and let me know if I can be helpful with fleshing out the list, as well!

**Comment by brandocalrissian** [comment]
I have a short list of things to add to the board. Will put them on the board after stand-up.

**Comment by brandocalrissian** [comment]
Added list of expected core KMS functions to the pipeline "Out of the box/table stakes functionality" on [the KMS board](https://github.com/18F/dos-ops-center-kms/issues#workspaces/dos-ops-center-kms-5c264892f9cceb5e65c195ee/boards?repos=163426891&showClosed=false&showEstimates=false)

**Comment by brandocalrissian** [comment]
Had the list out there for a few days. We can always add more to these later but I think that's a good start.
