### ISSUE TITLE
Create interview guide for Clarence Finney

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#95]
As an 18F Researcher I want to have a guide for asking questions and collecting information from our interview with Clarence Finney from Records Management so that we can get the most information out of the research in the shortest time possible.

- [ ] Create the interview guide

**Comment by yowill** [comment]
Records Management handles the "legally required" record-keeping, smart system, step system, etc.

**Comment by brandocalrissian** [comment]
Additional background:

Automated systems. Things that can be FOIAd. Things that need to be indexed. Cables. Anything that goes to President, interagency. Everything S brings to meetings at WH. Copies of emails.

Mostly an automatic process.

People there not responsible for digitizing records but rather setting up best practices to keep systems in compliance with legal requirements.

KMS may store records. Clarence Finney is the head of Records Management.
