### ISSUE TITLE
Schedule interview with Joe Wicentowski

### ISSUE THREAD

**Issue by karareinsel** [18F/dos-ops-center#99]
- [ ] Schedule the interview with Digital Historian Joe Wicentowski

**Comment by karareinsel** [comment]
@beebouttw I'm tagging you here for some extra air support. I'm not having any success getting in touch with Joe. I've sent multiple emails but so far no response. Thoughts? I'm tagging this as blocked.

**Comment by beebouttw** [comment]
I reached out to Joe separately to pose the question of a "followup" interview in the hopes of getting a response from him.  Currently awaiting, possibly blocked.

**Comment by karareinsel** [comment]
Closing this out since we've made multiple attempts to schedule an interview but have not had success.
